### ISSUE TITLE
does it support models from vllm?

### ISSUE THREAD

**Issue by xxm1668** [zjunlp/KnowLM#101]

**Comment by MikeDean2367** [comment]
As far as I know, vllm is a library for optimizing batch inferring, and it does not provide any models.

Our model supports vllm for inferring. You can refer to [it](https://docs.vllm.ai/en/latest/getting_started/quickstart.html) to deploy our model using vllm. You just set the `llm = LLM(model="facebook/opt-125m")` to `llm = LLM(model='zjunlp/knowlm-13b-zhixi')`.

Please let me know if you have any other questions.

**Comment by xxm1668** [comment]
thanks
