### ISSUE TITLE
在复现信息抽取结果时报错：TypeError: not a string

### ISSUE THREAD

**Issue by steven140811** [zjunlp/KnowLM#102]
python examples/generate_lora.py --base_model zjunlp/knowlm-13b-zhixi --run_ie_cases
testing ie ablities!
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data/package/lyp/model/KnowLM/examples/generate_lora.py:228 in <module>                         │
│                                                                                                  │
│   225                                                                                            │
│   226                                                                                            │
│   227 if __name__ == "__main__":                                                                 │
│ ❱ 228 │   fire.Fire(main)                                                                        │
│   229 │   """                                                                                    │
│   230 │   # multi-gpu                                                                            │
│   231 │   CUDA_VISIBLE_DEVICES=0,1,2,3 python examples/generate_lora.py --base_model zjunlp/kn   │
│                                                                                                  │
│ /data/conda_env/knowlm_lyp/lib/python3.9/site-packages/fire/core.py:141 in Fire                  │
│                                                                                                  │
│   138 │   context.update(caller_globals)                                                         │
│   139 │   context.update(caller_locals)                                                          │
│   140                                                                                            │
│ ❱ 141   component_trace = _Fire(component, args, parsed_flag_args, context, name)                │
│   142                                                                                            │
│   143   if component_trace.HasError():                                                           │
│   144 │   _DisplayError(component_trace)                                                         │
│                                                                                                  │
│ /data/conda_env/knowlm_lyp/lib/python3.9/site-packages/fire/core.py:475 in _Fire                 │
│                                                                                                  │
│   472 │     is_class = inspect.isclass(component)                                                │
│   473 │                                                                                          │
│   474 │     try:                                                                                 │
│ ❱ 475 │   │   component, remaining_args = _CallAndUpdateTrace(                                   │
│   476 │   │   â   component,                                                                     │
│   477 │   │   │   remaining_args,                                                                │
│   478 │   │   │   component_trace,                                                               │
│                                                                                                  │
│ /data/conda_env/knowlm_lyp/lib/python3.9/site-packages/fire/core.py:691 in _CallAndUpdateTrace   │
│                                                                                                  │
│   688 │   loop = asyncio.get_event_loop()                                                        │
│   689 │   component = loop.run_until_complete(fn(*varargs, **kwargs))                            │
│   690   else:                                                                                    │
│ ❱ 691 │   component = fn(*varargs, **kwargs)                                                     │
│   692                                                                                            │
│   693   if treatment == 'class':                                                                 │
│   694 │   action = trace.INSTANTIATED_CLASS                                                      │
│                                                                                                  │
│ /data/package/lyp/model/KnowLM/examples/generate_lora.py:117 in main                             │
│                                                                                                  │
│   114 │   ), "Please specify a --base_model, e.g. --base_model='decapoda-research/llama-7b-hf'   │
│   115 │                                                                                          │
│   116 │   prompter = Prompter(prompt_template)                                                   │
│ ❱ 117 │   tokenizer = LlamaTokenizer.from_pretrained(base_model)                                 │
│   118 │   print(f"load_8bit={load_8bit}")                                                        │
│   119 │                                                                                          │
│   120 │   if device == "cuda":                                                                   │
│                                                                                                  │
│ /data/conda_env/knowlm_lyp/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:1 │
│ 811 in from_pretrained                                                                           │
│                                                                                                  │
│   1808 │   │   │   else:                                                                         │
│   1809 │   │   │   │   logger.info(f"loading file {file_path} from cache at {resolved_vocab_fil  │
│   1810 │   │                                                                                     │
│ ❱ 1811 │   │   return cls._from_pretrained(                                                      │
│   1812 │   │   │   resolved_vocab_files,                                                         │
│   1813 │   │   │   pretrained_model_name_or_path,                                                │
│   1814 │   │   │   init_configuration,                                                           │
│                                                                                                  │
│ /data/conda_env/knowlm_lyp/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:1 │
│ 965 in _from_pretrained                                                                          │
│                                                                                                  │
│   1962 │   │                                                                                     │
│   1963 │   │   # Instantiate tokenizer.                                                          │
│   1964 │   │   try:                                                                              │
│ ❱ 1965 │   │   │   tokenizer = cls(*init_inputs, **init_kwargs)                                  │
│   1966 │   │   except OSError:                                                                   │
│   1967 │   │   │   raise OSError(                                                                │
│   1968 │   │   │   │   "Unable to load vocabulary from file. "                                   │
│                                                                                                  │
│ /data/conda_env/knowlm_lyp/lib/python3.9/site-packages/transformers/models/llama/tokenization_ll │
│ ama.py:96 in __init__                                                                            │
│                                                                                                  │
│    93 │   │   self.add_bos_token = add_bos_token                                                 │
│    94 │   │   self.add_eos_token = add_eos_token                                                 │
│    95 │   │   self.sp_model = spm.SentencePieceProcessor(**self.sp_model_kwargs)                 │
│ ❱  96 │   │   self.sp_model.Load(vocab_file)                                                     │
│    97 │                                                                                          │
│    98 │   def __getstate__(self):                                                                │
│    99 │   │   state = self.__dict__.copy()                                                       │
│                                                                                                  │
│ /data/conda_env/knowlm_lyp/lib/python3.9/site-packages/sentencepiece/__init__.py:905 in Load     │
│                                                                                                  │
│    902 │   │   raise RuntimeError('model_file and model_proto must be exclusive.')               │
│    903 │     if model_proto:                                                                     │
│    904 │   │   return self.LoadFromSerializedProto(model_proto)                                  │
│ ❱  905 │     return self.LoadFromFile(model_file)                                                │
│    906                                                                                           │
│    907                                                                                           │
│    908 # Register SentencePieceProcessor in _sentencepiece:                                      │
│                                                                                                  │
│ /data/conda_env/knowlm_lyp/lib/python3.9/site-packages/sentencepiece/__init__.py:310 in          │
│ LoadFromFile                                                                                     │
│                                                                                                  │
│    307 │   │   return _sentencepiece.SentencePieceProcessor_serialized_model_proto(self)         │
│    308 │                                                                                         │
│    309 │   def LoadFromFile(self, arg):                                                          │
│ ❱  310 │   │   return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)              │
│    311 │                                                                                         │
│    312 │   def _EncodeAsIds(self, text, enable_sampling, nbest_size, alpha, add_bos, add_eos, r  │
│    313 │   │   return _sentencepiece.SentencePieceProcessor__EncodeAsIds(self, text, enable_sam  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: not a string

模型下载的是knowlm-13b-zhixi
目录结构如下：
![image](https://github.com/zjunlp/KnowLM/assets/63778907/bff21cbd-9229-482f-bf5c-783c418ae5a0)

**Comment by MikeDean2367** [comment]
Can you provide your environment and GPU information?

**Comment by steven140811** [comment]
I have fixed this problem. I forgot to download the tokenizer.model (it is a git LFS file, so lower versions of git may ignore it while doing git clone), so I suppose anyone who got the incomplete file may encounter the same error. So make sure the file exists and the md5 checksum matches.
