### ISSUE TITLE
Input information on the web page, but no response is displayed

### ISSUE THREAD

**Issue by keyilizzie** [zjunlp/KnowLM#103]
Use the following command to access the web:

python examples/generate_lora_web.py --base_model zjunlp/knowlm-13b-zhixi
![Uploading WechatIMG995.png…]()

**Comment by MikeDean2367** [comment]
The uploaded image seems to be unable to load. Providing conda environment and GPU information will help solve this issue. Perhaps the terminal has provided error information?

**Comment by keyilizzie** [comment]
Hello,the conda environment and GPU information are following:
knowlm ,conda -V 4.14.0
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:16:03_PST_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0

**Comment by keyilizzie** [comment]
> 上传的图片似乎无法加载。提供conda环境和GPU信息将有助于解决这个问题。也许终端提供了错误信息？

Hello,the conda environment and GPU information are following:
knowlm ,conda -V 4.14.0
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:16:03_PST_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0

**Comment by MikeDean2367** [comment]
I didn't explain it clearly.  Do you use conda or docker? The `conda information` refers to the version of the package (), such as `transformers`, `torch`, `gradio`. The `GPU information` refers to the type and number of GPU used, such as 3090*8.

**Comment by keyilizzie** [comment]
> I didn't explain it clearly. Do you use conda or docker? The `conda information` refers to the version of the package (), such as `transformers`, `torch`, `gradio`. The `GPU information` refers to the type and number of GPU used, such as 3090*8.

GPU：Tesla V100-SXM2... *4
conda information：
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
accelerate                0.17.1                   pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
aiohttp                   3.8.6                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    5.1.2                    pypi_0    pypi
annotated-types           0.6.0                    pypi_0    pypi
anyio                     3.7.1                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
babel                     2.13.1                   pypi_0    pypi
bce-python-sdk            0.8.96                   pypi_0    pypi
bitsandbytes              0.37.2                   pypi_0    pypi
blinker                   1.7.0                    pypi_0    pypi
blis                      0.7.11                   pypi_0    pypi
ca-certificates           2023.08.22           h06a4308_0  
catalogue                 2.0.10                   pypi_0    pypi
certifi                   2023.7.22                pypi_0    pypi
charset-normalizer        3.3.1                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpathlib              0.16.0                   pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
colorlog                  6.7.0                    pypi_0    pypi
confection                0.1.3                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
cymem                     2.0.8                    pypi_0    pypi
datasets                  2.14.6                   pypi_0    pypi
dill                      0.3.4                    pypi_0    pypi
exceptiongroup            1.1.3                    pypi_0    pypi
fastapi                   0.104.0                  pypi_0    pypi
ffmpy                     0.3.1                    pypi_0    pypi
filelock                  3.12.4                   pypi_0    pypi
fire                      0.5.0                    pypi_0    pypi
flask                     3.0.0                    pypi_0    pypi
flask-babel               4.0.0                    pypi_0    pypi
fonttools                 4.43.1                   pypi_0    pypi
frozenlist                1.4.0                    pypi_0    pypi
fsspec                    2023.10.0                pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
gradio                    3.50.2                   pypi_0    pypi
gradio-client             0.6.1                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  0.18.0                   pypi_0    pypi
httpx                     0.25.0                   pypi_0    pypi
huggingface-hub           0.18.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.8.0                    pypi_0    pypi
importlib-resources       6.1.0                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
jsonschema                4.19.1                   pypi_0    pypi
jsonschema-specifications 2023.7.1                 pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
langcodes                 3.3.0                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.8.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
multiprocess              0.70.12.2                pypi_0    pypi
murmurhash                1.0.10                   pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  3.2                      pypi_0    pypi
numpy                     1.26.1                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.18.1                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.3.52                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
onnx                      1.15.0                   pypi_0    pypi
openssl                   3.0.11               h7f8727e_2  
orjson                    3.9.10                   pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
paddle2onnx               1.1.0                    pypi_0    pypi
paddlefsl                 1.1.0                    pypi_0    pypi
paddlenlp                 2.6.1                    pypi_0    pypi
pandas                    2.1.2                    pypi_0    pypi
peft                      0.5.0                    pypi_0    pypi
pillow                    10.1.0                   pypi_0    pypi
pip                       23.3.1                   pypi_0    pypi
preshed                   3.0.9                    pypi_0    pypi
protobuf                  3.20.2                   pypi_0    pypi
psutil                    5.9.6                    pypi_0    pypi
pyarrow                   13.0.0                   pypi_0    pypi
pycryptodome              3.19.0                   pypi_0    pypi
pydantic                  2.4.2                    pypi_0    pypi
pydantic-core             2.10.1                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.17.1                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
python                    3.9.18               h955ad1f_0  
python-dateutil           2.8.2                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
rarfile                   4.1                      pypi_0    pypi
readline                  8.2                  h5eee18b_0  
referencing               0.30.2                   pypi_0    pypi
regex                     2023.10.3                pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
rich                      13.7.0                   pypi_0    pypi
rpds-py                   0.10.6                   pypi_0    pypi
safetensors               0.4.0                    pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.11.4                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
seqeval                   1.2.2                    pypi_0    pypi
setuptools                68.0.0           py39h06a4308_0  
six                       1.16.0                   pypi_0    pypi
smart-open                6.4.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
spacy                     3.7.2                    pypi_0    pypi
spacy-legacy              3.0.12                   pypi_0    pypi
spacy-llm                 0.6.2                    pypi_0    pypi
spacy-loggers             1.0.5                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
srsly                     2.4.8                    pypi_0    pypi
starlette                 0.27.0                   pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
thinc                     8.2.1                    pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.3                   pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     2.1.0                    pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
transformers              4.28.1                   pypi_0    pypi
triton                    2.1.0                    pypi_0    pypi
typer                     0.9.0                    pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
urllib3                   2.0.7                    pypi_0    pypi
uvicorn                   0.23.2                   pypi_0    pypi
visualdl                  2.5.3                    pypi_0    pypi
wasabi                    1.1.2                    pypi_0    pypi
weasel                    0.3.3                    pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.41.2           py39h06a4308_0  
xxhash                    3.4.1                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0  
yarl                      1.9.2                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0

**Comment by MikeDean2367** [comment]
OK, i think you should execute the following command:
```bash
CUDA_VISIBLE_DEVICES=0,1,2,3 python examples/generate_lora_web.py --base_model zjunlp/knowlm-13b-zhixi --multi_gpu --allocate [4,9,9,9]
```
I run it successfully! Please make sure the code is latest. Please let me know if you have any other questions :)

**Comment by keyilizzie** [comment]
> OK, i think you should execute the following command:
> 
> ```shell
> CUDA_VISIBLE_DEVICES=0,1,2,3 python examples/generate_lora_web.py --base_model zjunlp/knowlm-13b-zhixi --multi_gpu --allocate [4,9,9,9]
> ```
> 
> I run it successfully! Please make sure the code is latest. Please let me know if you have any other questions :)

Thank you，I'll try again

**Comment by zxlzr** [comment]
Do you have any further questions?
