### ISSUE TITLE
Domestic model download issues

### ISSUE THREAD

**Issue by hzrlsd** [zjunlp/KnowLM#104]
Please add a copy of the HF model and make a download available on Modelscpoe at the same time
Thanks！

**Comment by zxlzr** [comment]
We will add the HF link soon.

**Comment by MikeDean2367** [comment]
In fact, adding `HF_ENDPOINT=https://hf-mirror.com` before the command can be downloaded domestically. Please feel free to refer to [this](https://zhuanlan.zhihu.com/p/668245670) for details. Here is an example:
```bash
HF_ENDPOINT=https://hf-mirror.com python examples/generate_finetune.py --base_model zjunlp/knowlm-13b-base-v1.0
```

**Comment by zxlzr** [comment]
Hi, we have uploaded models in the wisemodel and modelscope, feel free to contact us if you have any issues.
