### ISSUE TITLE
 resolving the problem of embodiment cognition in LLMs？

### ISSUE THREAD

**Issue by longjiaqiuu** [zjunlp/KnowLM#105]
文中说：
Knowledge Interaction: It enables dynamic knowledge interaction and feedback to achieve tool-based learning and multi-agent collaboration, resolving the problem of embodiment cognition in LLMs ([English Tutorial](https://github.com/zjunlp/KnowLM/blob/main/pdf/Knowledge_Interaction.pdf)).
没太看懂，作者可以帮忙展开解释一下么？该方式可以让AI知道自己所处的环境？

**Comment by zxlzr** [comment]
您好，这指的是大模型通过知识交互学习，实现工具调用和智能体Agent，目前仍在开发中未开源这部分功能。

**Comment by zxlzr** [comment]
请问您还有其他问题吗，我们计划在下一代版本发布基于知识库增强的工具调用等子工具和数据集。
