### ISSUE TITLE
KnowIM-13B-IE的inference 脚本使用失败。

### ISSUE THREAD

**Issue by Williamqiang** [zjunlp/KnowLM#110]
我首先将inference的代码适配到我的中文数据集上，发现报错。然后，使用你们提供的推理代码，除了修改model本地路径外，没有做其它的修改，但是依然出现和我自己数据集上一样的错误。![image](https://github.com/zjunlp/KnowLM/assets/50281702/6c43c23e-900d-4aef-8a8d-dbf7b412147b)

**Comment by Williamqiang** [comment]
transformers版本为4.37.0

**Comment by zxlzr** [comment]
您好我们会马上排查下问题。

**Comment by MikeDean2367** [comment]
您好，请问您提到的`inference.py`文件是哪个文件，在本仓库中似乎没有这个python文件。

**Comment by guihonghao** [comment]
你好，你可以试试accelerate==0.20.3

**Comment by guihonghao** [comment]
我们推荐的环境是torch==2.0.1
accelerate==0.20.3
transformers==4.30.2
bitsandbytes==0.39.1
peft==0.4.0
datasets==2.12.0
sentencepiece==0.1.98
scipy==1.10.1
protobuf==3.20.1
pydantic==1.10.7

**Comment by zxlzr** [comment]
请问您的问题是否已解决？
