### ISSUE TITLE
vLLM API服务报错

### ISSUE THREAD

**Issue by zhengyunzhao** [zjunlp/KnowLM#111]
请问在使用vLLM API服务时，下载vllm包之后，运行报ImportError: cannot import name 'DeviceID' from 'vllm.engine.ray_utils'
该如何解决

**Comment by MikeDean2367** [comment]
请问您使用的vllm的版本是多少？

由于我们目前仓库的vllm仅支持0.2.0，而vllm最新版本为0.3.2，我们建议使用最新的版本，具体教程参考[官方文档](https://docs.vllm.ai/en/latest/getting_started/quickstart.html)，由于我们的模型架构同llama，因此您安装最新的vllm后，可以使用下面的代码来运行并启动vllm api：
```bash
python -m vllm.entrypoints.openai.api_server \
    --model zjunlp/knowlm-13b-zhixi \
    --chat-template /path/to/your/template
```

您可以根据自己的需要，更改`--model`和`--chat-template`参数，其中后者可以参考[此处](https://github.com/vllm-project/vllm/tree/main/examples)。

如有问题，请告知我 :)

**Comment by zhengyunzhao** [comment]
安装了最新版本的vllm，使用的您[README_ZH.md](https://github.com/zjunlp/KnowLM/blob/main/README_ZH.md)提供的命令，模型换成了knowlm-13b-zhixi，如下：
max_num_batched_tokens=8000

CUDA_VISIBLE_DEVICES=1,2 python inference/launch_vllm.py \
    --port 8090 \
    --model zjunlp/knowlm-13b-zhixi \
    --use-np-weights \
    --max-num-batched-tokens $max_num_batched_tokens \
    --dtype half \
    --tensor-parallel-size 2
依旧会报错ImportError: cannot import name 'DeviceID' from 'vllm.engine.ray_utils'，请问命令里的参数需要修改么？

**Comment by MikeDean2367** [comment]
您好，安装最新的版本后，请不要运行readme中的命令，您可以参考[官方文档](https://docs.vllm.ai/en/latest/getting_started/quickstart.html)，或者使用下面的命令：
```bash
python -m vllm.entrypoints.openai.api_server \
    --model zjunlp/knowlm-13b-zhixi \
    --chat-template /path/to/your/template
```

**Comment by zxlzr** [comment]
请问您的问题是否已解决。

另外know-13b-zhixi 已经不是knowlm 系列最好的抽取模型了。您可以使用https://huggingface.co/zjunlp/knowlm-13b-ie  这个抽取效果更好一些（无通用能力）。您也可以适用我们的近期基于IEPile https://github.com/zjunlp/IEPile 的过度版本https://huggingface.co/zjunlp/baichuan2-13b-iepile-lora

我们即将发布新的能力更强的抽取模型 https://huggingface.co/zjunlp/knowlm-ie-v2
