### ISSUE TITLE
请问何时开源7b的zhixi大模型

### ISSUE THREAD

**Issue by StevenQAQ** [zjunlp/KnowLM#112]
请问何时开源7b的zhixi大模型

**Comment by zxlzr** [comment]
您好，因为没有足够的卡我们没有训7b的zhixi大模型，我们会即将发布13b的新版本抽取大模型https://huggingface.co/zjunlp/knowlm-13b-ie-v2 （计划月底发布）。

对于抽取大模型：

https://huggingface.co/zjunlp/knowlm-13b-ie

效果比zhixi更佳

抽取大模型v1和v2之间的过度版本：

https://huggingface.co/zjunlp/baichuan2-13b-iepile-lora

https://huggingface.co/zjunlp/llama2-13b-iepile-lora

对于7b模型有（因为没算力，这些模型没有达到最优，非常抱歉）：

https://huggingface.co/zjunlp/knowlm-7b-chat

https://huggingface.co/zjunlp/knowlm-7b-base
