### ISSUE TITLE
关于knowLM的使用

### ISSUE THREAD

**Issue by 66246764** [zjunlp/KnowLM#113]
您好，如果我想使用knowLM做垂直领域上的信息抽取任务，是直接下载模型“KnowLM-13B-ZhiXi”，然后运行“python examples/generate_lora.py --base_model zjunlp/knowlm-13b-zhixi --run_ie_cases”就可以使用了吗？还是需要通过处理垂直领域数据，通过lora微调这个“KnowLM-13B-ZhiXi”模型呢？
之前学习您的视频，上面说的是需要分别下载三个模型“LLaMa-13B”+“zhixi-13B-Diff” + “zhixi-13B-loRA”三个文件做权重还原还需要吗？在您的readme中好像都没单独提及这三个模型。

初学小白，问题可能比较奇怪请见谅

**Comment by MikeDean2367** [comment]
您好，直接运行下载，然后执行您提到的那个命令就可以运行了，之前的视频是老的版本，可以忽略。

**Comment by MikeDean2367** [comment]
如果使用lora微调，可以参考此处的[readme.md](https://github.com/zjunlp/KnowLM/tree/main/finetune/lora/knowlm)，对于模板的构造，可以修改[此处](https://github.com/zjunlp/KnowLM/blob/main/finetune/lora/knowlm/templates/alpaca.json)。

**Comment by 66246764** [comment]
您好，我下载了“KnowLM-13B-ZhiXi”模型，并配置了相关环境，成功复现了您论文中关于2.2中信息抽取的结果。
想请问一下如果下载好了所有模型文件以后，该模型是否可以离线使用呢？我注意到使用generate_lora.py后会有download的信息：
Downloading shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  3.60it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:32<00:00, 10.88s/it]
如果服务器不能接入互联网，是否会影响离线使用模型呢？

另外关于信息抽取可以直接在case里面写prompt吗，比如在下面实体抽取的例子中，我增加一点垂直领域的例子，是否会对结果有帮助呢？
ie_cases = {
    "从给定的文本中提取出可能的实体和实体类型，可选的实体类型为['产品', '指标']，以（实体，实体类型）的格式回答【例如“大多数机车的速度都在50h以上”，抽取结果为(“机车”，“产品”)，（“速度在50h以上”，“指标”）】。"+"[input]"+origin_sentence: {"num_beams":2, "temperature": 0.4, "repetition_penalty":1.3},
}
上面【例如“大多数机车的速度都在50h以上”，抽取结果为(“机车”，“产品”)，（“速度在50h以上”，“指标”）】这个内容是在您给的例子上增加的垂直领域数据的prompt，这种方式会有帮助吗？

**Comment by MikeDean2367** [comment]
对于第一个问题，只要离线下载好就可以使用，如果您需要迁移到新的机器上，您可以将`from_pretrained()`中的参数更改为模型的绝对路径。

对于第二个问题，您可以尝试一下，理论上来说可行，不过想要获得更好的效果，建议指令微调。

**Comment by 66246764** [comment]
明白了，谢谢您！
