### ISSUE TITLE
环境配置

### ISSUE THREAD

**Issue by HuiGe88** [zjunlp/KnowLM#114]
你好，我的显卡配置只有12G，想要复现信息抽取应该做哪些修改，若更换量化的llama模型能否实现？

**Comment by MikeDean2367** [comment]
您好，关于这个问题有两个解决方案：

1. **将GPU显存和CPU内存结合使用**。您可以使用下面的命令：
```bash
python examples/generate_lora_web.py --base_model zjunlp/knowlm-13b-zhixi --multi_gpu   --allocate [10]    
```
其中`--allocate`参数指的是模型占用多少显存，我在本地3090上测试，在推理的时候，峰值占用显存约为11GB，但是推理速度较慢。

2. **使用量化模型**。此处有两个潜在的方法，首先您可以参考[llama.cpp](https://github.com/ggerganov/llama.cpp)这个仓库对模型进行量化，然后进行推理。另外一个方法是直接在命令后加上`--load_4bit`，启用4比特量化，但是效果可能会受到影响，本地测试，4bit量化显存占用约8G。

如果仍有问题，请告知我 :)

**Comment by HuiGe88** [comment]
好的，非常感谢您的耐心解答

**Comment by HuiGe88** [comment]
您好，我采用您说的第一种方法将GPU与cpu内存结合使用，通过上面的命令行运行时，出现了以下报错，请问是怎么回事

ValueError: `checkpoint` should be the path to a file containing a whole state dict, or the index of a sharded checkpoint, or a folder containing a sharded checkpoint or the whole state dict, but got zjunlp/knowlm-13b-zhixi.

**Comment by MikeDean2367** [comment]
您好，我并没有出现您提到的问题，您可以尝试[此处](https://discuss.huggingface.co/t/load-checkpoint-and-dispatch-checkpoint-value-error-using-sagemaker/64743)的解决方案。

**Comment by zxlzr** [comment]
请问您还有什么问题吗
