### ISSUE TITLE
模型量化

### ISSUE THREAD

**Issue by HuiGe88** [zjunlp/KnowLM#115]
您好，请问如何通过Llama.cpp对Knowlm进行量化，能否提供一下具体步骤，谢谢您的解答。

**Comment by MikeDean2367** [comment]
您好，我们目前发布的模型的架构和llama相同，建议您查看llama.cpp的官方文档，里面提供了详细的步骤，或者您可以参考之前的issue，[#57](https://github.com/zjunlp/KnowLM/issues/57)，#60。如有问题，请告知我 :)

**Comment by zxlzr** [comment]
请问您还有什么问题吗

**Comment by HuiGe88** [comment]
您好，我现在已经通过llama.cpp对模型进行量化，得到了量化后的模型ggml-model-q4_0.gguf，接下来应该通过那些命令来调用模型进行信息抽取任务？

**Comment by MikeDean2367** [comment]
参考[此处](https://github.com/ggerganov/llama.cpp/blob/master/examples/alpaca.sh)的脚本运行即可。下面是可能需要修改的两个参数：
1. 将脚本的[第10行](https://github.com/ggerganov/llama.cpp/blob/50ccaf5eacb50a2ca378a4ef0dc7aeb45fead652/examples/alpaca.sh#L10)的`./models/alpaca.13b.ggmlv3.q8_0.bin`修改为您量化后的模型路径
2. 在输入的时候，请以下面的模板进行输入：
```python
"\n\n### Instruction:\n{instruction}\n\n### Input:\n{input}\n\n### Response:\n"
``` 
你需要将`{instruction}`和`{input}`替换为您的任务指令和输入文本。

**Comment by HuiGe88** [comment]
好的，谢谢您

**Comment by zxlzr** [comment]
请问您还有其他问题吗

**Comment by 63447285** [comment]
> 您好，我现在已经通过llama.cpp对模型进行量化，得到了量化后的模型ggml-model-q4_0.gguf，接下来应该通过那些命令来调用模型进行信息抽取任务？

请问你是怎么量化的，方便提供下量化后的模型吗？

**Comment by HuiGe88** [comment]
> > 您好，我现在已经通过llama.cpp对模型进行量化，得到了量化后的模型ggml-model-q4_0.gguf，接下来应该通过那些命令来调用模型进行信息抽取任务？
> 
> 请问你是怎么量化的，方便提供下量化后的模型吗？

上面作者已经给出了运行方法
