### ISSUE TITLE
请问一下lora指令微调knowlm可以用中文数据集吗？我用中文的会报错，改成英文就不会

### ISSUE THREAD

**Issue by exxaid** [zjunlp/KnowLM#118]

**Comment by MikeDean2367** [comment]
您好，是否可以提供一下报错的内容呢，理论上来说是与数据无关的

**Comment by exxaid** [comment]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\songyang\.conda\envs\lora\lib\site-packages\datasets\packaged_modules\json\json.py:121  │
│ in _generate_tables                                                                              │
│                                                                                                  │
│   118 │   │   │   │   │   │   try:                                                               │
│   119 │   │   │   │   │   │   │   while True:                                                    │
│   120 │   │   │   │   │   │   │   │   try:                                                       │
│ ❱ 121 │   │   │   │   │   │   │   │   │   pa_table = paj.read_json(                              │
│   122 │   │   │   │   │   │   │   │   │   │   io.BytesIO(batch), read_options=paj.ReadOptions(   │
│   123 │   │   │   │   │   │   │   │   │   )                                                      │
│   124 │   │   │   │   │   │   │   │   │   break                                                  │
│                                                                                                  │
│ in pyarrow._json.read_json:308                                                                   │
│                                                                                                  │
│ in pyarrow.lib.pyarrow_internal_check_status:154                                                 │
│                                                                                                  │
│ in pyarrow.lib.check_status:91                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ArrowInvalid: JSON parse error: Column() changed from object to array in row 0

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\songyang\.conda\envs\lora\lib\site-packages\datasets\builder.py:1973 in                 │
│ _prepare_split_single                                                                            │
│                                                                                                  │
│   1970 │   │   │   )                                                                             │
│   1971 │   │   │   try:                                                                          │
│   1972 │   │   │   │   _time = time.time()                                                       │
│ ❱ 1973 │   │   │   │   for _, table in generator:                                                │
│   1974 │   │   │   │   │   if max_shard_size is not None and writer._num_bytes > max_shard_size  │
│   1975 │   │   │   │   │   │   num_examples, num_bytes = writer.finalize()                       │
│   1976 │   │   │   │   │   │   writer.close()                                                    │
│                                                                                                  │
│ C:\Users\songyang\.conda\envs\lora\lib\site-packages\datasets\packaged_modules\json\json.py:144  │
│ in _generate_tables                                                                              │
│                                                                                                  │
│   141 │   │   │   │   │   │   │   │   with open(                                                 │
│   142 │   │   │   │   │   │   │   │   │   file, encoding=self.config.encoding, errors=self.con   │
│   143 │   │   │   │   │   │   │   │   ) as f:                                                    │
│ ❱ 144 │   │   │   │   │   │   │   │   │   dataset = json.load(f)                                 │
│   145 │   │   │   │   │   │   │   except json.JSONDecodeError:                                   │
│   146 │   │   │   │   │   │   │   │   logger.error(f"Failed to read file '{file}' with error {   │
│   147 │   │   │   │   │   │   │   │   raise e                                                    │
│                                                                                                  │
│ C:\Users\songyang\.conda\envs\lora\lib\json\__init__.py:293 in load                              │
│                                                                                                  │
│   290 │   To use a custom ``JSONDecoder`` subclass, specify it with the ``cls``                  │
│   291 │   kwarg; otherwise ``JSONDecoder`` is used.                                              │
│   292 │   """                                                                                    │
│ ❱ 293 │   return loads(fp.read(),                                                                │
│   294 │   │   cls=cls, object_hook=object_hook,                                                  │
│   295 │   │   parse_float=parse_float, parse_int=parse_int,                                      │
│   296 │   │   parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)          │
│                                                                                                  │
│ C:\Users\songyang\.conda\envs\lora\lib\codecs.py:322 in decode                                   │
│                                                                                                  │
│    319 │   def decode(self, input, final=False):                                                 │
│    320 │   │   # decode input (taking the buffer into account)                                   │
│    321 │   │   data = self.buffer + input                                                        │
│ ❱  322 │   │   (result, consumed) = self._buffer_decode(data, self.errors, final)                │
│    323 │   │   # keep undecoded input until the next call                                        │
│    324 │   │   self.buffer = data[consumed:]                                                     │
│    325 │   │   return result                                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 28: invalid start byte

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\PyCharm\Py_Projects\KnowLM\finetune\lora\knowlm\finetune.py:297 in <module>                   │
│                                                                                                  │
│   294                                                                                            │
│   295                                                                                            │
│   296 if __name__ == "__main__":                                                                 │
│ ❱ 297 │   fire.Fire(train)                                                                       │
│   298                                                                                            │
│                                                                                                  │
│ C:\Users\songyang\.conda\envs\lora\lib\site-packages\fire\core.py:143 in Fire                    │
│                                                                                                  │
│   140 │   context.update(caller_globals)                                                         │
│   141 │   context.update(caller_locals)                                                          │
│   142                                                                                            │
│ ❱ 143   component_trace = _Fire(component, args, parsed_flag_args, context, name)                │
│   144                                                                                            │
│   145   if component_trace.HasError():                                                           │
│   146 │   _DisplayError(component_trace)                                                         │
│                                                                                                  │
│ C:\Users\songyang\.conda\envs\lora\lib\site-packages\fire\core.py:477 in _Fire                   │
│                                                                                                  │
│   474 │     is_class = inspect.isclass(component)                                                │
│   475 │                                                                                          │
│   476 │     try:                                                                                 │
│ ❱ 477 │   │   component, remaining_args = _CallAndUpdateTrace(                                   │
│   478 │   │   │   component,                                                                     │
│   479 │   │   │   remaining_args,                                                                │
│   480 │   │   │   component_trace,                                                               │
│                                                                                                  │
│ C:\Users\songyang\.conda\envs\lora\lib\site-packages\fire\core.py:693 in _CallAndUpdateTrace     │
│                                                                                                  │
│   690 │   loop = asyncio.get_event_loop()                                                        │
│   691 │   component = loop.run_until_complete(fn(*varargs, **kwargs))                            │
│   692   else:                                                                                    │
│ ❱ 693 │   component = fn(*varargs, **kwargs)                                                     │
│   694                                                                                            │
│   695   if treatment == 'class':                                                                 │
│   696 │   action = trace.INSTANTIATED_CLASS                                                      │
│                                                                                                  │
│ D:\PyCharm\Py_Projects\KnowLM\finetune\lora\knowlm\finetune.py:215 in train                      │
│                                                                                                  │
│   212 │   model.print_trainable_parameters()  # Be more transparent about the % of trainable p   │
│   213 │                                                                                          │
│   214 │   if data_path.endswith(".json") or data_path.endswith(".jsonl"):                        │
│ ❱ 215 │   │   data = load_dataset("json",data_files=data_path)                                   │
│   216 │   │   print(f"data includes: {data_path}")                                               │
│   217 │   else:                                                                                  │
│   218 │   │   """is folder"""                                                                    │
│                                                                                                  │
│ C:\Users\songyang\.conda\envs\lora\lib\site-packages\datasets\load.py:2582 in load_dataset       │
│                                                                                                  │
│   2579 │   try_from_hf_gcs = path not in _PACKAGED_DATASETS_MODULES                              │
│   2580 │                                                                                         │
│   2581 │   # Download and prepare data                                                           │
│ ❱ 2582 │   builder_instance.download_and_prepare(                                                │
│   2583 │   │   download_config=download_config,                                                  │
│   2584 │   │   download_mode=download_mode,                                                      │
│   2585 │   │   verification_mode=verification_mode,                                              │
│                                                                                                  │
│ C:\Users\songyang\.conda\envs\lora\lib\site-packages\datasets\builder.py:1005 in                 │
│ download_and_prepare                                                                             │
│                                                                                                  │
│   1002 │   │   │   │   │   │   │   prepare_split_kwargs["max_shard_size"] = max_shard_size       │
│   1003 │   │   │   │   │   │   if num_proc is not None:                                          │
│   1004 │   │   │   │   │   │   │   prepare_split_kwargs["num_proc"] = num_proc                   │
│ ❱ 1005 │   │   │   │   │   │   self._download_and_prepare(                                       │
│   1006 │   │   │   │   │   │   │   dl_manager=dl_manager,                                        │
│   1007 │   │   │   │   │   │   │   verification_mode=verification_mode,                          │
│   1008 │   │   │   │   │   │   │   **prepare_split_kwargs,                                       │
│                                                                                                  │
│ C:\Users\songyang\.conda\envs\lora\lib\site-packages\datasets\builder.py:1100 in                 │
│ _download_and_prepare                                                                            │
│                                                                                                  │
│   1097 │   │   │                                                                                 │
│   1098 │   │   │   try:                                                                          │
│   1099 │   │   │   │   # Prepare split will record examples associated to the split              │
│ ❱ 1100 │   │   │   │   self._prepare_split(split_generator, **prepare_split_kwargs)              │
│   1101 │   │   │   except OSError as e:                                                          │
│   1102 │   │   │   │   raise OSError(                                                            │
│   1103 │   │   │   │   │   "Cannot find data file. "                                             │
│                                                                                                  │
│ C:\Users\songyang\.conda\envs\lora\lib\site-packages\datasets\builder.py:1860 in _prepare_split  │
│                                                                                                  │
│   1857 │   │   │   gen_kwargs = split_generator.gen_kwargs                                       │
│   1858 │   │   │   job_id = 0                                                                    │
│   1859 │   │   │   with pbar:                                                                    │
│ ❱ 1860 │   │   │   │   for job_id, done, content in self._prepare_split_single(                  │
│   1861 │   │   │   │   │   gen_kwargs=gen_kwargs, job_id=job_id, **_prepare_split_args           │
│   1862 │   │   │   │   ):                                                                        │
│   1863 │   │   │   │   │   if done:                                                              │
│                                                                                                  │
│ C:\Users\songyang\.conda\envs\lora\lib\site-packages\datasets\builder.py:2016 in                 │
│ _prepare_split_single                                                                            │
│                                                                                                  │
│   2013 │   │   │   │   e = e.__context__                                                         │
│   2014 │   │   │   if isinstance(e, DatasetGenerationError):                                     │
│   2015 │   │   │   │   raise                                                                     │
│ ❱ 2016 │   │   │   raise DatasetGenerationError("An error occurred while generating the dataset  │
│   2017 │   │                                                                                     │
│   2018 │   │   yield job_id, True, (total_num_examples, total_num_bytes, writer._features, num_  │
│   2019                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
DatasetGenerationError: An error occurred while generating the dataset

**Comment by MikeDean2367** [comment]
您好，我们的测试一切正常。根据您的错误信息，可能有如下两个方面的原因：
1. 请确保文件的编码格式为UTF-8
2. 请确保文件中的每个样本的格式一致

下面是我们随机使用的数据，命名为`dummy.json`:
```python
[
    {"instruction": "指令1", "input":"输入1", "output":"输出1"},
    {"instruction": "指令2", "input":"输入2", "output":"输出2"},
    {"instruction": "指令3", "input":"输入3", "output":"输出3"},
    {"instruction": "指令4", "input":"输入4", "output":"输出4"},
    {"instruction": "指令5", "input":"输入5", "output":"输出5"},
    {"instruction": "指令6", "input":"输入6", "output":"输出6"},
    {"instruction": "指令7", "input":"输入7", "output":"输出7"},
    {"instruction": "指令8", "input":"输入8", "output":"输出8"},
    {"instruction": "指令9", "input":"输入9", "output":"输出9"},
    {"instruction": "指令10", "input":"输入10", "output":"输出10"},
    {"instruction": "指令11", "input":"输入11", "output":"输出11"},
    {"instruction": "指令12", "input":"输入12", "output":"输出12"},
    {"instruction": "指令13", "input":"输入13", "output":"输出13"},
    {"instruction": "指令14", "input":"输入14", "output":"输出14"},
    {"instruction": "指令15", "input":"输入15", "output":"输出15"}
]
```

如仍有问题，请告知我 :)

**Comment by exxaid** [comment]
好的，是编码格式问题，感谢
