### ISSUE TITLE
是否有Dialogue Model这类信息抽取模型在常用IE数据集上的评测结果，如准确率，F1呢

### ISSUE THREAD

**Issue by AliceNCsyuk** [zjunlp/KnowLM#119]
您好，我看到github上有说明Dialogue Model是信息抽取模型，在case里面也展示了将文本转换为能用于构建KG的结构化数据的例子，然而自己并没有找到这些模型在常用IE数据集上的准确率与F1数据，不知道是否有这方面的评测结果？

**Comment by zxlzr** [comment]
请问您还有什么问题吗？
