### ISSUE TITLE
大规模数据读取费时

### ISSUE THREAD

**Issue by QingqingSun-Bao** [zjunlp/KnowLM#120]
请教一下，大规模数据读取的IO操作，导致gpu的利用率在部分时间为0，有没有什么方法能够避免这种情况，尽可能充分利用gpu的资源吗？

**Comment by MikeDean2367** [comment]
您好，您可以先事先离线对数据进行分词，然后存储在硬盘中，在训练开始之前加载，这样在训练的时候就不会有大量的io读写操作。此外，如果您的训练数据很大，您可以使用Lazy Loading技术加载数据。

如有问题，请告知我 :)

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
