### ISSUE TITLE
关于Lora指令微调权重获取与复原，这一部分的链接好像有问题，https://github.com/zjunlp/KnowLM/tree/main#22-%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E6%9D%83%E9%87%8D%E8%8E%B7%E5%8F%96%E4%B8%8E%E6%81%A2%E5%A4%8D

### ISSUE THREAD

**Issue by exxaid** [zjunlp/KnowLM#121]

**Comment by MikeDean2367** [comment]
您好，我们发布的模型已经不用权重复原和获取了，您提到的内容已经过时。

如仍有问题，请告知我 :)

**Comment by exxaid** [comment]
> 您好，我们发布的模型已经不用权重复原和获取了，您提到的内容已经过时。
> 
> 如仍有问题，请告知我 :)

那请问微调后应该怎么使用这个模型呢

**Comment by MikeDean2367** [comment]
您好，您可以将[此处](https://github.com/zjunlp/KnowLM/blob/5ffa8d66dd421b9b7d0eebe49cc22f51ebed94a1/examples/generate_lora.py#L138)的代码解除注释即可（需要注释的行数包括138～142，149～154，160～164）：
https://github.com/zjunlp/KnowLM/blob/5ffa8d66dd421b9b7d0eebe49cc22f51ebed94a1/examples/generate_lora.py#L138

如有问题，请告知我 :)

**Comment by exxaid** [comment]
ValueError: Can't find 'adapter_config.json' at ''
请问一下这个报错怎么解决呢

**Comment by MikeDean2367** [comment]
您好，`adapter_config.json`是lora的配置文件，在执行命令的时候请使用`--lora_weights`传入您的lora路径。

如仍有问题，请告知我 :)

**Comment by exxaid** [comment]
好的，非常感谢

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
