### ISSUE TITLE
二次训练

### ISSUE THREAD

**Issue by HuiGe88** [zjunlp/KnowLM#123]
您好，请问该模型可以在我的个人数据集上进行二次训练吗？

**Comment by zxlzr** [comment]
您好，可以二次训练，建议混入通用数据避免模型灾难性遗忘。

**Comment by HuiGe88** [comment]
您好，我还有个问题，能否提供该模型数据集的转换脚本，我想要使用我的数据集进行测试，这是我的数据集格式：
{"text": "现任金科地产集团股份有限公司执行总裁。", "entity": [{"entity": "执行总裁", "entity_type": "职位"}]}

**Comment by zxlzr** [comment]
您好，您可以按照模型数据的格式自行转换一下数据。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
