### ISSUE TITLE
您好，我想在自己的数据集上对经过llama.cpp量化的zhixi大模型进行评估，我应该怎么做，能否给出一些指导，非常感谢您的帮助。

### ISSUE THREAD

**Issue by HuiGe88** [zjunlp/KnowLM#124]

**Comment by HuiGe88** [comment]
您好，我想在自己的数据集上对经过llama.cpp量化的zhixi大模型进行评估，我应该怎么做，能否给出一些指导，非常感谢您的帮助。

**Comment by MikeDean2367** [comment]
您好，您可以参考这个[仓库](https://github.com/abetlen/llama-cpp-python)，它提供了使用python的方法来加载由llama.cpp量化的模型，之后，您可以像往常一样进行批量的评估即可。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by HuiGe88** [comment]
暂时没有了，谢谢
