### ISSUE TITLE
评价指标Rouge

### ISSUE THREAD

**Issue by orangezfj** [zjunlp/KnowLM#125]
您好，项目里面有关于Rouge-2评估关系抽取结果的代码嘛？想要借鉴一下

**Comment by guihonghao** [comment]
你好，你可以参考https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/ie2instruction/eval/metric/metric.py

**Comment by orangezfj** [comment]
好的！感谢您的回复！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月17日(周三) 中午11:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjunlp/KnowLM] 评价指标Rouge (Issue #125)




 
你好，你可以参考https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/ie2instruction/eval/metric/metric.py
