### ISSUE TITLE
下载zip解压，按步骤操作，报OSError

### ISSUE THREAD

**Issue by hzr764108561** [zjunlp/KnowLM#126]
testing ie ablities!
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\knowledge_graph\KnowLM-main\examples\generate_lora.py:232 in <module>                         │
│                                                                                                  │
│   229                                                                                            │
│   230                                                                                            │
│   231 if __name__ == "__main__":                                                                 │
│ ❱ 232 │   fire.Fire(main)                                                                        │
│   233 │   """                                                                                    │
│   234 │   # multi-gpu                                                                            │
│   235 │   CUDA_VISIBLE_DEVICES=0,1,2,3 python examples/generate_lora.py --base_model zjunlp/kn   │
│                                                                                                  │
│ D:\anaconda3\envs\knowlm\lib\site-packages\fire\core.py:143 in Fire                              │
│                                                                                                  │
│   140 │   context.update(caller_globals)                                                         │
│   141 │   context.update(caller_locals)                                                          │
│   142                                                                                            │
│ ❱ 143   component_trace = _Fire(component, args, parsed_flag_args, context, name)                │
│   144                                                                                            │
│   145   if component_trace.HasError():                                                           │
│   146 │   _DisplayError(component_trace)                                                         │
│                                                                                                  │
│ D:\anaconda3\envs\knowlm\lib\site-packages\fire\core.py:477 in _Fire                             │
│                                                                                                  │
│   474 │     is_class = inspect.isclass(component)                                                │
│   475 │                                                                                          │
│   476 │     try:                                                                                 │
│ ❱ 477 │   │   component, remaining_args = _CallAndUpdateTrace(                                   │
│   478 │   │   │   component,                                                                     │
│   479 │   │   │   remaining_args,                                                                │
│   480 │   │   │   component_trace,                                                               │
│                                                                                                  │
│ D:\anaconda3\envs\knowlm\lib\site-packages\fire\core.py:693 in _CallAndUpdateTrace               │
│                                                                                                  │
│   690 │   loop = asyncio.get_event_loop()                                                        │
│   691 │   component = loop.run_until_complete(fn(*varargs, **kwargs))                            │
│   692   else:                                                                                    │
│ ❱ 693 │   component = fn(*varargs, **kwargs)                                                     │
│   694                                                                                            │
│   695   if treatment == 'class':                                                                 │
│   696 │   action = trace.INSTANTIATED_CLASS                                                      │
│                                                                                                  │
│ D:\knowledge_graph\KnowLM-main\examples\generate_lora.py:118 in main                             │
│                                                                                                  │
│   115 │   ), "Please specify a --base_model, e.g. --base_model='decapoda-research/llama-7b-hf'   │
│   116 │                                                                                          │
│   117 │   prompter = Prompter(prompt_template)                                                   │
│ ❱ 118 │   tokenizer = LlamaTokenizer.from_pretrained(base_model)                                 │
│   119 │   print(f"load_8bit={load_8bit}")                                                        │
│   120 │                                                                                          │
│   121 │   if device == "cuda":                                                                   │
│                                                                                                  │
│ D:\anaconda3\envs\knowlm\lib\site-packages\transformers\tokenization_utils_base.py:1795 in       │
│ from_pretrained                                                                                  │
│                                                                                                  │
│   1792 │   │   │   )                                                                             │
│   1793 │   │                                                                                     │
│   1794 │   │   if all(full_file_name is None for full_file_name in resolved_vocab_files.values(  │
│ ❱ 1795 │   │   │   raise EnvironmentError(                                                       │
│   1796 │   │   │   │   f"Can't load tokenizer for '{pretrained_model_name_or_path}'. If you wer  │
│   1797 │   │   │   │   "'https://huggingface.co/models', make sure you don't have a local direc  │
│   1798 │   │   │   │   f"Otherwise, make sure '{pretrained_model_name_or_path}' is the correct   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: Can't load tokenizer for 'zjunlp/knowlm-13b-zhixi'. If you were trying to load it from
'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure
'zjunlp/knowlm-13b-zhixi' is the correct path to a directory containing all relevant files for a LlamaTokenizer
tokenizer.

**Comment by hzr764108561** [comment]
尝试跑这条指令 python examples/generate_lora.py --base_model zjunlp/knowlm-13b-zhixi --run_ie_cases

**Comment by MikeDean2367** [comment]
您好，请检查您的目录中是否有`zjunlp/knowlm-13b-zhixi`文件夹，如果有，请确保里面含有分词器`tokenizer.model`。如果仍然不行，您可以尝试手动下载所有的文件，然后将`--base_model`设为您保存的目录。

如仍有问题，请告知我 :)

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

另外我们发布了新的抽取大模型OneKE（无通用能力，只能做抽取），如果您有抽取需求可以试用下，欢迎您提意见。
