### ISSUE TITLE
训练数据集

### ISSUE THREAD

**Issue by HuiGe88** [zjunlp/KnowLM#129]
您好，请问能否提供该模型ner和re指令训练数据集所用到的所有实体类型和关系类型，非常感谢您的帮助

**Comment by zxlzr** [comment]
您好，请问您问的什是什么模型？如果您问的是OneKE，部分训练数据已经在IEPile公开了您可以自行下载统计。

**Comment by HuiGe88** [comment]
智析大模型

**Comment by zxlzr** [comment]
您好，我们这没有统计过的确切数字，抱歉，如果我没记错的话抽取部分的数据已开源https://huggingface.co/datasets/zjunlp/knowlm-ke  ，其中一部分清洗过的数据还开源在https://huggingface.co/datasets/zjunlp/InstructIE

**Comment by HuiGe88** [comment]
好的，谢谢
