### ISSUE TITLE
环境配置pip下载不成功

### ISSUE THREAD

**Issue by xppzs** [zjunlp/KnowLM#131]
pip install torch==1.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116这条指令下载不下来

![Uploading 7ad41d0ed64ffbaae9ee7a34b978328.png…]()

**Comment by MikeDean2367** [comment]
您好，您上传的图片似乎看不了，无法看出报错的内容，请再提供一下，或者直接粘贴错误内容 :)

**Comment by zxlzr** [comment]
请问您的问题解决了吗？
