### ISSUE TITLE
使用knowlm-13b-zhix不能复现效果

### ISSUE THREAD

**Issue by SwordfallYeung** [zjunlp/KnowLM#132]
操作系统环境：openEuler 22.03
显卡：两张各25GB的RTX A5000
环境变量设置：
export BNB_CUDA_VERSION=122
export PATH=/usr/local/cuda-12.2/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.2/lib64
依赖包版本：
bitsandbytes==0.43.1
transformers== 4.41.2
peft==0.5.0

执行命令：CUDA_VISIBLE_DEVICES=1 python examples/generate_lora_web.py --base_model ../zjunlp/knowlm-13b-zhixi --run_general_cases

结果：能正常运行
![Uploading 智析_20240607190310.png…]()

问题：请问output怎么把红框后面多余的数据去掉？

**Comment by MikeDean2367** [comment]
您好，我们已经修复这个问题，请您使用最新的代码运行。

此外，我们推荐您使用我们最新的模型，[OneKE](https://huggingface.co/zjunlp/OneKE)，运行代码为：
```bash
CUDA_VISIBLE_DEVICES=1 python examples/generate_lora_web.py --base_model zjunlp/oneke --run_general_cases
```

如有其他问题，请告知我 :)

**Comment by zxlzr** [comment]
请问您还有其他问题吗

**Comment by SwordfallYeung** [comment]
谢谢，暂时没有啦
