### ISSUE TITLE
复现信息抽取时运行代码报错

### ISSUE THREAD

**Issue by dengfan2018** [zjunlp/KnowLM#133]
若希望[复现信息抽取](https://github.com/zjunlp/KnowLM/blob/main/README_ZH.md#22-%E4%BF%A1%E6%81%AF%E6%8A%BD%E5%8F%96%E6%95%88%E6%9E%9C)的结果，请运行如下命令：

python examples/generate_lora.py --base_model zjunlp/knowlm-13b-zhixi --run_ie_cases

TypeError: __init__() got an unexpected keyword argument 'load_in_4bit'
![image](https://github.com/zjunlp/KnowLM/assets/40187266/0e3fb765-6d04-43ad-a21c-3a019ab0d4fc)

**Comment by MikeDean2367** [comment]
您好，我本地测试没问题，应该是环境配置问题，您可以参考这个[issue](https://github.com/TimDettmers/bitsandbytes/issues/428)。如仍有问题，请告知我 :)

**Comment by zxlzr** [comment]
您还有其他问题吗？
