### ISSUE TITLE
python examples/generate_lora_web.py --base_model zjunlp/knowlm-13b-zhixi命令报错

### ISSUE THREAD

**Issue by xiang-hui744** [zjunlp/KnowLM#135]
<img width="821" alt="image" src="https://github.com/zjunlp/KnowLM/assets/57001862/1f04f6d4-c407-4193-ab13-d7b3f6adced2">
报错ImportError: cannot import name 'is_npu_available' from 'accelerate.utils' 
求解决

**Comment by MikeDean2367** [comment]
您好，请安装最新版本的accelerate包，可以参考这个[issue](https://github.com/huggingface/transformers/issues/26744)。

**Comment by zxlzr** [comment]
hi, do you have any further questions?
