### ISSUE TITLE
 TypeError: __init__() got an unexpected keyword argument 'load_in_4bit'

### ISSUE THREAD

**Issue by xiang-hui744** [zjunlp/KnowLM#136]
如题，求指教！

**Comment by lh5533223** [comment]
我有同样的问题，就是KnowLM-13B-ZhiXi智析的权重文件之后，运行python examples/generate_lora.py --base_model zjunlp/knowlm-13b-zhixi --run_ie_cases想复现信息抽取结构，而和楼主一样的报错！求解，谢谢

**Comment by lh5533223** [comment]
I have the same problem, that is, after KnowLM-13B-ZhiXi's weight file, Run python examples/generate_lora.py --base_model zjunlp/knowlm-13b-zhixi --run_ie_cases want to repeat the information extraction structure, and the same error as the floor! Solve it, thank you

**Comment by MikeDean2367** [comment]
Hello, the issue seems to stem from an environmental configuration problem. Please refer to this [issue](https://github.com/TimDettmers/bitsandbytes/issues/428) for guidance. If the problem persists, please let me know :)

**Comment by lh5533223** [comment]
> Hello, the issue seems to stem from an environmental configuration problem. Please refer to this [issue](https://github.com/TimDettmers/bitsandbytes/issues/428) for guidance. If the problem persists, please let me know :)

Hello, I installed the environment exactly as in the requirements.txt file of the konwml file. Could you please see where the configuration is wrong?

**Comment by lh5533223** [comment]
> Hello, the issue seems to stem from an environmental configuration problem. Please refer to this [issue](https://github.com/TimDettmers/bitsandbytes/issues/428) for guidance. If the problem persists, please let me know :)

![Uploading 环境.png…]()

**Comment by lh5533223** [comment]
> Hello, the issue seems to stem from an environmental configuration problem. Please refer to this [issue](https://github.com/TimDettmers/bitsandbytes/issues/428) for guidance. If the problem persists, please let me know :)

The libraries in the file are:
gradio
Bitsandbytes = = 0.37.2
datasets
sentencepiece
fire
Accelerate the = = 0.17.1
Transformers = = 4.28.1
peft

**Comment by lh5533223** [comment]
Can you help me?

**Comment by xiang-hui744** [comment]
> Can you help me?

<img width="769" alt="image" src="https://github.com/zjunlp/KnowLM/assets/57001862/318c6d0f-db14-47ce-a19b-8e977c4a23bc">
I commented this part of the code

**Comment by lh5533223** [comment]
> code

Thank you very much. After making this code change, the TypeError error mentioned above is resolved. But after running the python examples/generate_lora_web.py --base_model zjunlp/knowlm-13b-zhixi command
Loading checkpoint shards:  100% | █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ ██████| 3/3 [00:35<00:00, 11.69s/it]
Running on local URL: http://0.0.0.0:7860
Visit http://0.0.0.0:7860 and this message appears: A problem of "This page cannot be accessed There may be a problem with the page at http://0.0.0.0:7860/ or it has permanently moved to a new address." 
Could you still help me, please?
