### ISSUE TITLE
ValueError: Can't read templates/./bloom_deploy.json.json

### ISSUE THREAD

**Issue by piggie-zjui** [zjunlp/KnowLM#137]
![屏幕截图 2024-06-21 094050](https://github.com/zjunlp/KnowLM/assets/172457547/62d48d1c-fb4f-4fc9-bb21-c4f03c5f1ce7)
after i run bash ./scripts/infer.sh, (I am follow the instruction to modify infer.sh) and there are files  in the folders, what's wrong? (deleting .json doesn't help)

**Comment by MikeDean2367** [comment]
Hello, it appears that our repository does not contain these scripts. Could you please check the source of the code?

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by piggie-zjui** [comment]
> Hello, it appears that our repository does not contain these scripts. Could you please check the source of the code?

Thanks for your advice, finally I found in other file that 'templates' and '.json' have already been written for me .

**Comment by piggie-zjui** [comment]
> hi, do you have any further questions?

problem solves, thanks
