### ISSUE TITLE
底座模型复现问题

### ISSUE THREAD

**Issue by luohao123** [zjunlp/KnowLM#14]
![image](https://github.com/zjunlp/CaMA/assets/49749220/e1762a94-1770-4d4c-ab3e-c923ccdd6719)

花了10kuai q块钱淘宝买的预训练模型，借了一个64GB的服务区，花了一上午时间转了一波，竟然是这个结果。

如果结果不对，还请在README写明，完全无法复现。。。。

**Comment by zxlzr** [comment]
您好，请问您是否按readme合并了diff和lora参数呢，模型输出的结果和gpu超参数等多个因素有关，烦请提供下您的超参数我们检查下。目前模型主要定位是抽取任务，在其他任务还存在很多不足非常抱歉。

**Comment by MikeDean2367** [comment]
您好，非常抱歉给您造成了困扰。我不是很明白您的意思，我的理解是您使用了我们的`CaMA-13B`的二次预训练模型（即将`LLaMA-13B`与`CaMA-13B-Diff`进行权重合并），然后得到了这个结果。下面的回答都是基于您按照上面的步骤进行。

首先是您的`prompt`与我们提供的不同，在`README`中，我们加粗体的部分为`prompt`，因此正确的`prompt`应该为`你很擅长将中文翻译成英文。将下面的句子翻译成英文：我们今天准备去西安看兵马俑。答案：`，您少了`答案：`，此外此处的[代码](https://github.com/zjunlp/CaMA/blob/main/examples/generate_finetune.py#L27)也写明了这一点。

接着您并没有给出解码的超参数。我们在`readme`中也说明了这一点，解码超参数对于模型的解码结果影响较大。如果您想复现我们的结果，可以直接使用[此处](https://github.com/zjunlp/cama#24-%E6%A8%A1%E5%9E%8B%E4%BD%BF%E7%94%A8)的脚本进行复现。

如果您尝试了上述的步骤仍为解决，请告知我。

**Comment by luohao123** [comment]
我肯定合并了diff，你们既没有提供转换后的MD5，也没有在某个地方让用户验证是否成功。
我用脚本和按照readme的步骤，无法复线 **预训练模型的**生成能力。

**Comment by zxlzr** [comment]
烦请您按例子里提供的prompt试一试，如果有问题麻烦提供一下超参数

**Comment by zxlzr** [comment]
> 我肯定合并了diff，你们既没有提供转换后的MD5，也没有在某个地方让用户验证是否成功。
> 
> 我用脚本和按照readme的步骤，无法复线 **预训练模型的**生成能力。

您的prompt少了 答案： 。底座模型是语言模型基本没有指令理解能力的

**Comment by luohao123** [comment]
我试了一下lora，感觉能力不符合预期。

![image](https://github.com/zjunlp/CaMA/assets/49749220/46f668c2-a0ab-4a0a-bf54-a503cc1724e9)


可能是什么yuan y原因导致的？

另外我看输出经常的出现乱码，倒不是说乱码不正常，而是我试了很多其他中文模型，都不会出现这么高概率的乱码，除了直接在llama底座上微调的。

是否跟你们没有扩充此表有关？

**Comment by MikeDean2367** [comment]
您好，出现乱码的原因我们在[此处](https://github.com/zjunlp/CaMA/tree/main#6-faq)做了说明。

如果是在文本结尾出现乱码属于正常现象，因为中文由多个token组成，可能**最后输出的时候刚好不够凑成一个中文字符**，但是到达了设定的最大解码参数，这个问题到不能说是乱码，您可以通过调整输出长度来解决（其他的扩充词表的方法，基本上都是一个中文汉字对应于一个token，因此不会在结尾出现乱码）；

如果是在文本中间出现了乱码，建议您更换`prompt`，但是在我们的大量测试中，出现第二种情况很少，建议您尝试调整prompt，或更改解码参数。

最后关于您提到的能力，我们使用`LoRA`微调，指令数据集的分布在[此处](https://github.com/zjunlp/CaMA/tree/main#33-%E6%8C%87%E4%BB%A4%E5%BE%AE%E8%B0%83%E6%95%B0%E6%8D%AE%E9%9B%86%E6%9E%84%E5%BB%BA)提到，由于目前的大语言模型层出不穷，均千篇一律，受限于模型参数等问题性能都几乎无法达到`ChatGPT`的性能，因此我们对**信息抽取**场景进行优化。其余的性能测试您可以尝试更改解码参数或者调整prompt来获得其他结果。

希望这个回答能帮助到您 :)
