### ISSUE TITLE
运行指令“python examples/generate_finetune_web.py --base_model zjunlp/knowlm-13b-base-v1.0”出现"嗯… 无法访问此页面网址为http://0.0.0.0:7860/ 的页面可能存在问题，或者已永久移动到新的网址。"报错

### ISSUE THREAD

**Issue by lh5533223** [zjunlp/KnowLM#141]

**Comment by lh5533223** [comment]
终端出现：cuda
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:37<00:00, 12.58s/it]
Running on local URL:  http://0.0.0.0:7860

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.

**Comment by MikeDean2367** [comment]
请问您是在服务器上运行的吗，如果是，请确保内网穿透正常

**Comment by lh5533223** [comment]
> 请问您是在服务器上运行的吗，如果是，请确保内网穿透正常

好的，谢谢你。

**Comment by lh5533223** [comment]
> 请问您是在服务器上运行的吗，如果是，请确保内网穿透正常

![image](https://github.com/zjunlp/KnowLM/assets/84327800/11cb9fa9-73da-44bb-918c-de95666f4fb0)
你好，我在运行"python examples/generate_lora_web.py --base_model knowlm-13b-zhixi  "指令复现基于 Web 的交互效果时，点击“提交”按钮之后，右侧Output栏总是报Error，并且源码终端代码就结束执行了。

**Comment by lh5533223** [comment]
你好，可以帮我一下吗？
我运行“python examples/generate_finetune_web.py --base_model zjunlp/knowlm-13b-base-v1.0”这个指令的web交互是没有问题的！

**Comment by MikeDean2367** [comment]
您好，我本地测试正常，请确保使用仓库的最新代码，如果仍报错，请提供所使用的gradio版本，我使用的gradio版本是`3.50.2`。

**Comment by zxlzr** [comment]
请问您的问题是否已解决？
