### ISSUE TITLE
关于vllm服务部署oneke模型 参数设置问题

### ISSUE THREAD

**Issue by SwordfallYeung** [zjunlp/KnowLM#144]
环境：
vllm版本: 0.5.0.post1

执行命令：
`CUDA_VISIBLE_DEVICES=4,5 /data/anaconda3/envs/knowlm/bin/python -m vllm.entrypoints.openai.api_server --model /data/knowlm/zjunlp/OneKE --dtype auto  --api-key token-abc123 --tensor-parallel-size 2`

问题1：
使用上述执行命令，oneke模型参数如何设置，看inference/launch_vllm.py源码或者运行generate_lora_web.py显示的界面
![image](https://github.com/zjunlp/KnowLM/assets/15890940/110ad521-f519-4d22-bd7d-cd2b89c2811e)
![image](https://github.com/zjunlp/KnowLM/assets/15890940/a10a1905-d543-4b2f-99b7-0c09d2ccfc0c)
这些参数不用管？但我看文档介绍，设置这些参数可以使精度提高，而且看了前面的issue是建议直接用最新的vllm上面类似代码跑的

问题2：
第一看generate_lora_web.py源码，里面有默认设置的load_8bit和load_4bit参数设置，第二看Deepke文档介绍运行OneKe模型时候提供一段代码
```
# 4bit量化OneKE
quantization_config=BitsAndBytesConfig(
    load_in_4bit=True,
    llm_int8_threshold=6.0,
    llm_int8_has_fp16_weight=False,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)
```
那么直接使用vllm服务部署OneKe模型的时候，好像都没有设置这些量化参数，是可以不用设置么

本人小白，刚接触大模型不久，如有问的比较简单，敬请原谅。

因为发现问题1和问题2涉及的参数跑了OneKE模型，精度有提高，但是直接使用vllm跑的OneKE模型精度有降低

下面用的是openspg教程里面提供的案例的，分别用generate_lora_web.py和DeepKE oneke教程的代码跑下面的语句
`{"instruction": "你是一个图谱实体知识结构化专家。根据输入实体类型(entity type)的schema描述，从文本中抽取出相应的实体实例和其属性信息，不存在的属性不输出, 属性存在多值就返回列表，并输出为可解析的json格式。", "schema": [{"entity_type": "疾病", "attributes": ["适用药品", "常见症状", "就诊科室", "发病部位", "并发症", "异常指征"]}, {"entity_type": "人体部位", "attributes": ["别名", "是"]}, {"entity_type": "药品", "attributes": []}, {"entity_type": "医院科室", "attributes": ["别名", "是"]}], "input": "甲状腺结节是指在甲状腺内的肿块，可随吞咽动作随甲状腺而上下移动，是临床常见的病症，可由多种病因引起。临床上有多种甲状腺疾病，如甲状腺退行性变、炎症、自身免疫以及新生物等都可以表现为结节。甲状腺结节可以单发，也可以多发，多发结节比单发结节的发病率高，但单发结节甲状腺癌的发生率较高。患者通常可以选择在普外科，甲状腺外科，内分泌科，头颈外科挂号就诊。有些患者可以触摸到自己颈部前方的结节。在大多情况下，甲状腺结节没有任何症状，甲状腺功能也是正常的。甲状腺结节进展为其它甲状腺疾病的概率只有1%。有些人会感觉到颈部疼痛、咽喉部异物感，或者存在压迫感。当甲状腺结节发生囊内自发性出血时，疼痛感会更加强烈。治疗方面，一般情况下可以用放射性碘治疗，复方碘口服液(Lugol液)等，或者服用抗甲状腺药物来抑制甲状腺激素的分泌。目前常用的抗甲状腺药物是硫脲类化合物，包括硫氧嘧啶类的丙基硫氧嘧啶(PTU)和甲基硫氧嘧啶(MTU)及咪唑类的甲硫咪唑和卡比马唑。"}`

generate_lora_web.py和DeepKE oneke教程的代码执行结果如下：
```
{
	"疾病": {
		"甲状腺结节": {
			"适用药品": [
				"复方碘口服液",
				"抗甲状腺药物",
				"硫脲类化合物",
				"丙基硫氧嘧啶",
				"甲基硫氧嘧啶",
				"甲硫咪唑",
				"卡比马唑"
			],
			"常见症状": "颈部疼痛、咽喉部异物感，或者存在压迫感",
			"就诊科室": [
				"普外科",
				"甲状腺外科",
				"内分泌科",
				"头颈外科"
			]
		},
		"甲状腺退行性变": {
			"发病部位": "甲状腺"
		},
		"炎症": {
			"发病部位": "甲状腺"
		},
		"自身免疫": {
			"发病部位": "甲状腺"
		},
		"新生物": {
			"发病部位": "甲状腺"
		}
	}
}
```
vllm服务跑的OneKE模型执行结果，常见症状 json不规范，多添加了格外的数据，或者“常见症状”会变成“症状”，而不是“常见症状”：
```
{"疾病": 
  {  
    "甲状腺结节": 
     {
	 "适用药品": [
	"复方碘口服液",
	"抗甲状腺药物",
	"硫氧嘧啶类的丙基硫氧嘧啶",
	"甲基硫氧嘧啶",
	"咪唑类的甲硫咪唑和卡比马唑"
], 
	 "常见症状": ["颈部疼痛、咽喉部异物感，或者存在压迫感", "胸部、颈部、肩部等症状》》》", 
	 "就诊科室": ["普外科", "甲状腺外科", "内分泌科", "头颈外科"], 
	 "发病部位": "甲状腺"
	 }, 
	 "甲状腺退行性变": {"发病部位": "甲状腺"}, 
	 "炎症": {"发病部位": "甲状腺"}, 
	 "自身免疫": {"发病部位": "甲状腺"}, 
	 "单发结节甲状腺癌": {"发病部位": "甲状腺"}, 
	 "多发结节": {"发病部位": "甲状腺"}
	 }
}
```

发现vllm服务部署的oneke效果精度降低了一些，想根据上述两个问题提问一下，谢谢

**Comment by MikeDean2367** [comment]
您好，可以不用量化，关于vllm，下面是一个极简代码：
```python
from vllm import LLM, SamplingParams
sampling_params = SamplingParams(
            temperature=0.0, top_p=1.0, max_tokens=200)
model=LLM(model="your path")
output = model.generate(
    ["your prompt"],
    sampling_params=sampling_params
)
print(output[0].outputs[0].text)
```
此处的`SamplingParams`控制了的参数，详细文档参考[此处](https://docs.vllm.ai/en/stable/dev/sampling_params.html#vllm.SamplingParams)。另外一个需要注意的点是，`your prompt`需要包含特殊的token，根据[此处](https://github.com/zjunlp/DeepKE/blob/main/example/llm/OneKE.md)的文档，`your prompt`应当为：
```python
system_prompt = '<<SYS>>\nYou are a helpful assistant. 你是一个乐于助人的助手。\n<</SYS>>\n\n'
sintruct = "{\"instruction\": \"You are an expert in named entity recognition. Please extract entities that match the schema definition from the input. Return an empty list if the entity type does not exist. Please respond in the format of a JSON string.\", \"schema\": [\"person\", \"organization\", \"else\", \"location\"], \"input\": \"284 Robert Allenby ( Australia ) 69 71 71 73 , Miguel Angel Martin ( Spain ) 75 70 71 68 ( Allenby won at first play-off hole )\"}"
sintruct = '[INST] ' + system_prompt + sintruct + '[/INST]'
your_prompt=sintruct
```
然后执行这个python代码即可。如仍有问题，请告知我 :)

**Comment by MikeDean2367** [comment]
如果需要量化，可以参考官方[文档](https://docs.vllm.ai/en/latest/quantization/fp8.html)，具体来说，在上面的代码中，在`LLM()`类的初始化时传入相应的参数即可，比如`quantization="fp8"`或`quantization="AWQ"`。

**Comment by SwordfallYeung** [comment]
好的，非常感谢

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
