### ISSUE TITLE
请问我执行generate_lora.py文件抽取三元组时候非常耗时，这种情况正常吗？

### ISSUE THREAD

**Issue by lh5533223** [zjunlp/KnowLM#145]

**Comment by MikeDean2367** [comment]
如果撇开硬件速度、期望输出本身就很长、num beam设为很大的值这三种情况，则是有问题的，此时观察输出大概率是因为没有输出终止符号，通常情况下是重复输出，您可以调整`repetition_penalty`参数缓解这种情况。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
