### ISSUE TITLE
微调Qwen模型失败

### ISSUE THREAD

**Issue by zhl98** [zjunlp/KnowLM#147]
你好，非常感谢你们的工作。我在尝试knowlm后想要继续微调一下Qwen模型，使用的命令是
`CUDA_VISIBLE_DEVICES=0 accelerate launch finetune.py --data_path KnowLM-main/finetune/lora/knowlm/data/alpaca_data_cleaned.json --base_model Qwen1.5-7B-Chat/ --lora_target_modules '["c_attn", "c_proj", "w1", "w2"]' --prompt_template_name "qwen" --eval_steps 50  --save_steps 50`

但是他报错
ValueError: Target modules {'w1', 'c_proj', 'w2', 'c_attn'} not found in the base model. Please check the target modules and try again.

我尝试过Qwen2和Qwen1.5，发现都报错，是只支持Qwen吗？

**Comment by MikeDean2367** [comment]
您好，qwen的lora可选的值应当为["down_proj", "up_proj", "gate_proj", "k_proj", "o_proj", "q_proj", "v_proj"]

**Comment by zhl98** [comment]
好的，我微调成功了，非常感谢你的解答。
