### ISSUE TITLE
关于baseline

### ISSUE THREAD

**Issue by Gary-code** [zjunlp/KnowLM#148]

**Comment by Gary-code** [comment]
这个工作很有趣，我有一些疑惑关于和baseline的对比。
在文章4.1小节提到的basleine也是通过同样的实验setting进行微调吗？还是只是OCEANGPT基于LLaMA-2进行了微调。而ChatGLM2等baseline对比模型直接用于测评？

**Comment by zxlzr** [comment]
感谢您对工作的关注，基线是没有微调的，oceangpt论文里的版本是在llama2基础上经过预训练+微调（基于海洋领域指令）的；基线是通用指令微调模型，也就是对比了llama2 + 海洋预训练 + 海洋指令 vs 其他模型(含llama2) + 通用指令。严格来讲是需要对比 llama2 + 海洋指令 + 通用指令 vs 其他base模型 + 海洋指令 + 通用指令； 因算力有限我们没有卡做更多的实验。

另外，llama2版本模型已过时，目前我们已更新发布了qwen https://huggingface.co/zjunlp/OceanGPT-7b-v0.2 和minicpm的 https://huggingface.co/zjunlp/OceanGPT-2B-v0.1  及 qwen1.5-14b https://huggingface.co/zjunlp/OceanGPT-14B-v0.1 模型，14b效果略好（参数量最大）

因算力实在有限，更新优化进度比较慢抱歉
