### ISSUE TITLE
可以在不联网的状态下运行这个模型吗？

### ISSUE THREAD

**Issue by lurf131** [zjunlp/KnowLM#149]
已经下载了模型，后在不联网的状态下运行generate_lora和generate_lora_web，输入一段文字进行实体提取。目前已经run了快20分钟，都没有结果输出。请问是正常的吗？

**Comment by MikeDean2367** [comment]
您好，模型不需要联网运行。您可以尝试将beams设为1，然后将max_new_tokens设为10，查看能否输出内容。如果仍有问题，请告知我 :)

**Comment by lurf131** [comment]
>你好，现在是新的问题了。运行generate_lora_web，出现问题如下：
RuntimeError:
CuDA Setup failed despite GPu being available, Inspect the CuDA SETuP outputs above to fix your environment
If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:

**Comment by lurf131** [comment]
CUDA SETUP: CUDA detection failed! Possible reasons:1. CUDA driver not installed
2. CUDA not installed
3.You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUA SETuP: If you compiled from source, try again with "maKe CUDA VERSION=DETECTED CUDA VERSION’for example, *maKe CUDA VERSION=113'CUDA SETup: The CuDA version for the compile might depend on your conda install. Inspect cuDA version via 'conda list l grep cuda

**Comment by lurf131** [comment]
您说：
CUDA SETUP: CUDA detection failed! Possible reasons:1. CUDA driver not installed
2. CUDA not installed
3.You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUA SETuP: If you compiled from source, try again with "maKe CUDA VERSION=DETECTED CUDA VERSION’for example, *maKe CUDA VERSION=113'CUDA SETup: The CuDA version for the compile might depend on your conda install. Inspect cuDA version via 'conda list l grep cuda.  CUDA SETUP: Something unexpected happened. Please compile from source:git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA VERSION=123
python setup.py install
CUDA SETUP: Setup Failed!
CUDA SETUP: Something unexpected happened. Please compile from source:git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA VERSION=123
python setup.py install  RuntimeError:
CUDA Setup failed despite GPu being available. Inspect the CuDA SETuP outputs above to fix your environment!
If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:

**Comment by MikeDean2367** [comment]
您好，应该是您的环境问题，建议在linux系统上进行运行

**Comment by lurf131** [comment]
是的，我就是在linux上运行的。lora-web不行运行。lora可以运行。但是Lora的运行速度很忙，我都没有修改input，就是源代码的input，大概生成了20多分钟(我用了2个gpu）。

**Comment by lurf131** [comment]
> 您好，模型不需要联网运行。您可以尝试将beams设为1，然后将max_new_tokens设为10，查看能否输出内容。如果仍有问题，请告知我 :)

我按照您说的进行修改，运行速度变快了，但是只能输出一点点，想请问一下你们运行长tokens的也是这么慢的吗？

**Comment by zxlzr** [comment]
您好，运行速度取决于长度、gpu和系统配置和模型大小等，如果您想输出快一些可以使用vllm（readme有说明）或量化模型。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
