### ISSUE TITLE
关于模型大小的问题

### ISSUE THREAD

**Issue by lucasjinreal** [zjunlp/KnowLM#17]
这个13b为什么模型bin加起来有50GB？这不科学啊，原版13b好像是24GB

**Comment by MikeDean2367** [comment]
您好，我们的`CaMA`预训练版本实际上采用`fp16`格式存储大小也约为24GB，但是由于`LLaMA`权重的版权问题，我们不能直接提供预训练的`CaMA`，我们提供的是`CaMA`与`LLaMA`权重作差的结果，我们的权重作差代码参考[stanford alpaca](https://github.com/tatsu-lab/stanford_alpaca/blob/main/weight_diff.py)。

关于发布的`Diff`为什么是50GB，原因是我们采用的是`fp32`格式进行存储，因此会比原来的大一倍（**我们尝试过对`Diff`使用`fp16`格式进行存储，但是在恢复后与原来的有差异**）。

关于合并后的模型为什么是50GB，我们实际上加载的时候会转换成`fp16`格式，因此您可以额外在写一个脚本，直接将模型保存为`fp16`格式即可。

此外，我们后续也会发布新的版本。

**Comment by lucasjinreal** [comment]
@MikeDean2367  那和原版的float·16模型，还原differ的时候，我再保存为float16，是否跟你训练的结果是对齐的？

**Comment by MikeDean2367** [comment]
您好，只要按照步骤还原后，生成的fp32格式的模型可以直接保存为fp16格式，结果是对齐的。[此处](https://github.com/zjunlp/CaMA/blob/main/examples/generate_finetune.py#L62)的代码也说明了这一点，即在实际使用的时候用的也是fp16格式。
