### ISSUE TITLE
新的13b模型何时更新？

### ISSUE THREAD

**Issue by lucasjinreal** [zjunlp/KnowLM#18]
很高兴看到一个新的名字，然而换汤不换药，之前说13b还在继续训练，大概何时可以放出新的预训练模型？
因为下载一次46GB的模型，生命就消耗了50%，为了节省生命，需要明确一下预期时间。另外建议用fp16分发权重。。

**Comment by MikeDean2367** [comment]
您好，感谢您的关注。目前仅更换了项目的名称，因为未来会扩展至非LLaMA模型系列。关于下次全量训练更新的节点，受限于算力和时间因素，暂时无法确定具体时间。我们会在近期更新一版新的LoRA权重，并发布7B权重和新的权重分发方式。

**Comment by zxlzr** [comment]
非常抱歉13B模型给您的使用带来了不便，我们将在近期提供百度网盘和GoogleDrive方式下载权重。这个项目会在未来提供非Llama系列的模型如Falcon所以我们修改了项目名字和模型名字。

**Comment by zxlzr** [comment]
您好，我们已提供GoogleDrive 下载地址https://drive.google.com/drive/folders/1PZDqZNaBJYQYeON1-9aFBtagktEWAtUK diff权重，https://drive.google.com/drive/folders/1GLyaWIyDIayudrQhb_tJYoNPAUk1xByS lora权重。因为我们算力和人力等资源有限优化速度非常慢非常抱歉。

**Comment by lucasjinreal** [comment]
感谢，不过我的诉求并不是下载，hf下载超快的.... 考虑上传fp16的权重 下一次....

**Comment by MikeDean2367** [comment]
您好，我们目前还在转换，近期会传，性能可能会受到一些影响。

**Comment by lucasjinreal** [comment]
另外你们真的不考虑扩充词表么，baichuan的词表已经到64k了。

**Comment by MikeDean2367** [comment]
您好，我们暂时没有算力扩充词表来进行全量训练，未来算力充足会扩充词表进行全量训练

**Comment by zxlzr** [comment]
您好我们已上传fp16 diff  https://huggingface.co/zjunlp/zhixi-13b-diff-fp16, 非常感谢您的建议。

**Comment by SaraiQX** [comment]
> 很高兴看到一个新的名字，然而换汤不换药，之前说13b还在继续训练，大概何时可以放出新的预训练模型？ 因为下载一次46GB的模型，生命就消耗了50%，为了节省生命，需要明确一下预期时间。另外建议用fp16分发权重。。

哈哈哈哈 大佬这么逗吗？不过下载模型这梗我有替换（只是原因不一样）😂
