### ISSUE TITLE
是否支持加载33b 65b模型？

### ISSUE THREAD

**Issue by cristianoc20** [zjunlp/KnowLM#21]
请问这个代码是否支持加载33b 65b的llama?

**Comment by MikeDean2367** [comment]
您好，预训练代码、lora训练代码、推理代码均支持参数量更大的llama。您可能需要修改一下相应的超参数。

**Comment by cristianoc20** [comment]
好的 谢谢哈

Jintian Zhang ***@***.***>于2023年6月18日 周日09:09写道：
