### ISSUE TITLE
在经典公开NER数据集效果是？

### ISSUE THREAD

**Issue by guotong1988** [zjunlp/KnowLM#25]
多谢！

**Comment by zxlzr** [comment]
您好，我们模型目前还没有在公开NER数据集完整测试过，我们手动使用了一些case进行了测试，一般常见的实体（如人名、地名）可以被识别，一些复杂实体类型目前仍较难抽取。此外目前模型在三元组抽取效果较好，但性能受prompt影响很大，您可以参考https://github.com/zjunlp/KnowLM/blob/main/examples/ie_prompt.py 中的prompt。           

目前模型仍在迭代优化中，我们计划在暑期更新一个v2版本。
