### ISSUE TITLE
在python tools/weight_diff.py recover --path_raw ./converted --path_diff ./zhixi-diff --path_tuned ./zhixi这一步出现如下问题：

### ISSUE THREAD

**Issue by weiyrhub** [zjunlp/KnowLM#26]
在
python tools/weight_diff.py recover --path_raw ./converted --path_diff ./zhixi-diff --path_tuned ./zhixi
或
python tools/weight_diff.py recover --path_raw ./converted --path_diff ./zhixi-diff-fp16 --path_tuned ./zhixi --is_fp16 True

这步出现如下问题：

AssertionError: Naive integrity check failed. This could imply that some of the checkpoint files are corrupted.

请问这是什么原因呢？谢啦~

**Comment by MikeDean2367** [comment]
您好，这个错误说明您下载的diff文件或者llama13b存在问题，请重新下载。

**Comment by weiyrhub** [comment]
①、用的LLaMA-13B模型是从下面网址下载的：
https://ipfs.io/ipfs/QmPCfCEERStStjg4kfj3cmCUu1TP7pVQbxdFMwnhpuJtxk/
目录如下：
-rwxr-xr-x  1 root root               157             Jun 19 11:06             checklist.chk
-rwxr-xr-x  1 root root       13016334699     Jun 19 11:12     consolidated.00.pth
-rwxr-xr-x  1 root root       13016334699     Jun 19 11:16     consolidated.01.pth
-rwxr-xr-x  1 root root               101             Jun 19 11:16             params.json
使用如下代码转换LLaMA-13B模型
python convert_llama_weights_to_hf.py --input_dir ./ --model_size 13B --output_dir ./converted
 这一步没问题
②、zhixi-diff是从huggingface下载的：
https://huggingface.co/zjunlp/zhixi-13b-diff
-------------------------------------------------------------------------------------------------------------------------
请问这两个文件下载地址可以吗？我是用的这两个地址下载的文件进行的合并，还是会出现上述问题。

**Comment by MikeDean2367** [comment]
您好，这个错误的出现是说您合并后得到的权重与我们实际的权重有差异。您可以在`weight_diff.py`文件的第106行下方输出一下`allsum`变量的值。

**Comment by suizhibo** [comment]
请问解决了么？我也是遇到了这个问题，并且llama13B 已经下载了多次，且每次的MD5相同。另外zhixi-diff-fp16相关文件的MD5值也已对比且相同

**Comment by MikeDean2367** [comment]
您好，您下载的llama13b是来自哪里的呢？如果是这个链接https://huggingface.co/decapoda-research/llama-13b-hf ，在我们的实验是可以合并的，我们下载的`decapoda-research`的llama13b的权重md5码如下：
```shell
28356e816ac778e9e68a3a9be744ae25  pytorch_model-00001-of-00041.bin
9c5126239ac2a2d077c49d830b24d00e  pytorch_model-00002-of-00041.bin
acb4fbf2c8d1f37dd2667e71906d7d42  pytorch_model-00003-of-00041.bin
906f54e28ff7971c70194e6b69651155  pytorch_model-00004-of-00041.bin
930b5fae4a426d141e7adad9422cce44  pytorch_model-00005-of-00041.bin
797d3e6297281090bbbf8e0156d0e454  pytorch_model-00006-of-00041.bin
b7b5505dc8d5a52d3c5e11467fa3c5fd  pytorch_model-00007-of-00041.bin
dbe06bd04fdeffcd7d2eac0002c3559a  pytorch_model-00008-of-00041.bin
6b6e32f8a47a0ca45a1cfbf5b0ada98e  pytorch_model-00009-of-00041.bin
6d4215c830c2062ed84d5dfdd77074f9  pytorch_model-00010-of-00041.bin
d6a220d04c53c674159c463327ada027  pytorch_model-00011-of-00041.bin
776c09df20bd9d0d76a1d809df33d9ac  pytorch_model-00012-of-00041.bin
58ba7541cb5222654ccce7be73c71da9  pytorch_model-00013-of-00041.bin
549fe6eabe272c32a276ac132559ab5c  pytorch_model-00014-of-00041.bin
8a8416ebb7ba49ec65dc4e8b8fda6cca  pytorch_model-00015-of-00041.bin
cbf81222271ccd9cd1fa3bfb2c2f4968  pytorch_model-00016-of-00041.bin
60582451303400bd60b373f3b1d863c8  pytorch_model-00017-of-00041.bin
5af7bef80cbd8b3f3ccbda4b4865611d  pytorch_model-00018-of-00041.bin
d2ecf15033c8e779d5ba77d0e7574147  pytorch_model-00019-of-00041.bin
c3e82214a6695c53f8519bf97a58833c  pytorch_model-00020-of-00041.bin
da7672945efe7e4a795f385df0aeb3f6  pytorch_model-00021-of-00041.bin
1f44d5b6a67a3c05adc76b7af5d642a0  pytorch_model-00022-of-00041.bin
4701037834afcb09f0cfa7e927b5f42c  pytorch_model-00023-of-00041.bin
dc4f90f6c0de077076dbe719c5c4256f  pytorch_model-00024-of-00041.bin
2ee86394dca2346ddbfae86f2a1e5e97  pytorch_model-00025-of-00041.bin
754b8dcd8e19d293781f8673db6b3f96  pytorch_model-00026-of-00041.bin
668f575d193003908395efea7c083ee2  pytorch_model-00027-of-00041.bin
a0f0edc84a0854f8ac09037138dfdeb0  pytorch_model-00028-of-00041.bin
31fcd428722575b57090a4739094ffa3  pytorch_model-00029-of-00041.bin
3ccad19422f84343228b9270c972cf7a  pytorch_model-00030-of-00041.bin
143fdb4fba7c32ca001413b54fe5c225  pytorch_model-00031-of-00041.bin
541d68adcedcd9e15cb1e112702b0617  pytorch_model-00032-of-00041.bin
75a1202ab1f943dfe39c644fcca4e141  pytorch_model-00033-of-00041.bin
f5be2ca8cd3c27683ed3ed03007a24de  pytorch_model-00034-of-00041.bin
f263ec5bc0501e66ea9a724ce5e01d2f  pytorch_model-00035-of-00041.bin
5d0ee4cef574b87e791c7eda100ed4dd  pytorch_model-00036-of-00041.bin
8a29d8cc767f94d597fa684a929c3e51  pytorch_model-00037-of-00041.bin
87fe9a4403151d7a2ed0c9b817f8df2f  pytorch_model-00038-of-00041.bin
9522fb05117207bc8b8a1fb2a6bc881d  pytorch_model-00039-of-00041.bin
480fefd9a78ec0a80239f3b72bca3784  pytorch_model-00040-of-00041.bin
ae14e6676e953b9ce08d2184ae113a31  pytorch_model-00041-of-00041.bin
```

如果您不是使用这个llama13b，请告知我 :)，或者加我的微信`Oxygen2367`，备注`KnowLM`

**Comment by suizhibo** [comment]
> 您好，您下载的llama13b是来自哪里的呢？如果是这个链接https://huggingface.co/decapoda-research/llama-13b-hf ，在我们的实验是可以合并的，我们下载的`decapoda-research`的llama13b的权重md5码如下：
> 
> ```shell
> 28356e816ac778e9e68a3a9be744ae25  pytorch_model-00001-of-00041.bin
> 9c5126239ac2a2d077c49d830b24d00e  pytorch_model-00002-of-00041.bin
> acb4fbf2c8d1f37dd2667e71906d7d42  pytorch_model-00003-of-00041.bin
> 906f54e28ff7971c70194e6b69651155  pytorch_model-00004-of-00041.bin
> 930b5fae4a426d141e7adad9422cce44  pytorch_model-00005-of-00041.bin
> 797d3e6297281090bbbf8e0156d0e454  pytorch_model-00006-of-00041.bin
> b7b5505dc8d5a52d3c5e11467fa3c5fd  pytorch_model-00007-of-00041.bin
> dbe06bd04fdeffcd7d2eac0002c3559a  pytorch_model-00008-of-00041.bin
> 6b6e32f8a47a0ca45a1cfbf5b0ada98e  pytorch_model-00009-of-00041.bin
> 6d4215c830c2062ed84d5dfdd77074f9  pytorch_model-00010-of-00041.bin
> d6a220d04c53c674159c463327ada027  pytorch_model-00011-of-00041.bin
> 776c09df20bd9d0d76a1d809df33d9ac  pytorch_model-00012-of-00041.bin
> 58ba7541cb5222654ccce7be73c71da9  pytorch_model-00013-of-00041.bin
> 549fe6eabe272c32a276ac132559ab5c  pytorch_model-00014-of-00041.bin
> 8a8416ebb7ba49ec65dc4e8b8fda6cca  pytorch_model-00015-of-00041.bin
> cbf81222271ccd9cd1fa3bfb2c2f4968  pytorch_model-00016-of-00041.bin
> 60582451303400bd60b373f3b1d863c8  pytorch_model-00017-of-00041.bin
> 5af7bef80cbd8b3f3ccbda4b4865611d  pytorch_model-00018-of-00041.bin
> d2ecf15033c8e779d5ba77d0e7574147  pytorch_model-00019-of-00041.bin
> c3e82214a6695c53f8519bf97a58833c  pytorch_model-00020-of-00041.bin
> da7672945efe7e4a795f385df0aeb3f6  pytorch_model-00021-of-00041.bin
> 1f44d5b6a67a3c05adc76b7af5d642a0  pytorch_model-00022-of-00041.bin
> 4701037834afcb09f0cfa7e927b5f42c  pytorch_model-00023-of-00041.bin
> dc4f90f6c0de077076dbe719c5c4256f  pytorch_model-00024-of-00041.bin
> 2ee86394dca2346ddbfae86f2a1e5e97  pytorch_model-00025-of-00041.bin
> 754b8dcd8e19d293781f8673db6b3f96  pytorch_model-00026-of-00041.bin
> 668f575d193003908395efea7c083ee2  pytorch_model-00027-of-00041.bin
> a0f0edc84a0854f8ac09037138dfdeb0  pytorch_model-00028-of-00041.bin
> 31fcd428722575b57090a4739094ffa3  pytorch_model-00029-of-00041.bin
> 3ccad19422f84343228b9270c972cf7a  pytorch_model-00030-of-00041.bin
> 143fdb4fba7c32ca001413b54fe5c225  pytorch_model-00031-of-00041.bin
> 541d68adcedcd9e15cb1e112702b0617  pytorch_model-00032-of-00041.bin
> 75a1202ab1f943dfe39c644fcca4e141  pytorch_model-00033-of-00041.bin
> f5be2ca8cd3c27683ed3ed03007a24de  pytorch_model-00034-of-00041.bin
> f263ec5bc0501e66ea9a724ce5e01d2f  pytorch_model-00035-of-00041.bin
> 5d0ee4cef574b87e791c7eda100ed4dd  pytorch_model-00036-of-00041.bin
> 8a29d8cc767f94d597fa684a929c3e51  pytorch_model-00037-of-00041.bin
> 87fe9a4403151d7a2ed0c9b817f8df2f  pytorch_model-00038-of-00041.bin
> 9522fb05117207bc8b8a1fb2a6bc881d  pytorch_model-00039-of-00041.bin
> 480fefd9a78ec0a80239f3b72bca3784  pytorch_model-00040-of-00041.bin
> ae14e6676e953b9ce08d2184ae113a31  pytorch_model-00041-of-00041.bin
> ```
> 
> 如果您不是使用这个llama13b，请告知我 :)，或者加我的微信`Oxygen2367`，备注`KnowLM`
我的下载地址：
https://agi.gpt4.org/llama/LLaMA/13B/consolidated.00.pth
https://agi.gpt4.org/llama/LLaMA/13B/consolidated.01.pth

**Comment by MikeDean2367** [comment]
您好，请校验一下这两个文件的`md5码`：
```shell
0804c42ca65584f50234a86d71e6916a  consolidated.00.pth
016017be6040da87604f77703b92f2bc  consolidated.01.pth
```

并确保已经使用[此处](https://github.com/zjunlp/KnowLM#22-%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E6%9D%83%E9%87%8D%E8%8E%B7%E5%8F%96%E4%B8%8E%E6%81%A2%E5%A4%8D)的脚本文件进行转换。

**Comment by suizhibo** [comment]
> 您好，请校验一下这两个文件的`md5码`：
> 
> ```shell
> 0804c42ca65584f50234a86d71e6916a  consolidated.00.pth
> 016017be6040da87604f77703b92f2bc  consolidated.01.pth
> ```
> 
> 并确保已经使用[此处](https://github.com/zjunlp/KnowLM#22-%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B%E6%9D%83%E9%87%8D%E8%8E%B7%E5%8F%96%E4%B8%8E%E6%81%A2%E5%A4%8D)的脚本文件进行转换。

consolidated.00.pth，consolidated.01.pth的MD5值一样，且tensor(94047.9062)。
建议注释掉断言：
```python
assert torch.allclose(
            allsum, torch.full_like(allsum, fill_value=94052.2891 if not is_fp16 else 94046.1875), atol=1e-2, rtol=0
        ), "Naive integrity check failed. This could imply that some of the checkpoint files are corrupted."
```
然后重新执行
```python
python tools/weight_diff.py recover --path_raw ./converted --path_diff ./zhixi-diff-fp16 --path_tuned ./zhixi --is_fp16 True
```
接着可以计算zhixi目录下模型的MD5值，并于[此处](https://github.com/zjunlp/KnowLM#274-zhixi-13b-base)比较。
![a1a59c4b3075b0edfe251858be74ecf](https://github.com/zjunlp/KnowLM/assets/28916595/3baaae68-0314-440c-9059-0cc421063b21)

**Comment by MikeDean2367** [comment]
您好，经过多个用户对于`fp16`格式合并的反馈，我们原来的这个校验方法存在问题，因此我们对于`fp16`取消了这种校验方式（建议对`md5`码进行校验）。感谢您的反馈 :)

**Comment by zxlzr** [comment]
非常感谢您的建议，我们将更新校验脚本和readme，非常抱歉带来了不便。

**Comment by zxlzr** [comment]
请问您的问题解决了吗
