### ISSUE TITLE
lora微调训练时间

### ISSUE THREAD

**Issue by shuangshuangguo** [zjunlp/KnowLM#27]
您好，想请教一下在您的实验中，lora微调的数据集大小、batch size、token序列长度、训练速度和时长等相关信息，谢谢！

**Comment by MikeDean2367** [comment]
您好，感谢您的关注，下面是相关信息：
**数据集大小：** 参考[此处](https://github.com/zjunlp/KnowLM/tree/main#33-%E6%8C%87%E4%BB%A4%E5%BE%AE%E8%B0%83%E6%95%B0%E6%8D%AE%E9%9B%86%E6%9E%84%E5%BB%BA)的表格

**batch size**：4096

**token长度**：512

**训练设备**：8卡V100(32GB)

**训练速度**：432s/batch

**训练时长**：3 epoch共耗时约4.7天

**Comment by shuangshuangguo** [comment]
非常感谢您的回复！
