### ISSUE TITLE
Unable to load weights from pytorch checkpoint file for

### ISSUE THREAD

**Issue by suizhibo** [zjunlp/KnowLM#31]
python tools/weight_diff.py recover --path_raw ./converted --path_diff ./zhixi-diff-fp16 --path_tuned ./zhixi --is_fp16 True

----------------------------------------------------------------------------------------------------------------------------------------
OSError: Unable to load weights from pytorch checkpoint file for './zhixi-diff-fp16/pytorch_model-00001-of-00003.bin' at 
'./zhixi-diff-fp16/pytorch_model-00001-of-00003.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by MikeDean2367** [comment]
您好，我推测应该是下载的权重不完整的问题，请检查一下您下载的三个权重文件（`zhixi-13b-diff-fp16`）的md5码：
```shell
37322209a703e24bb0b06d2742901741  pytorch_model-00001-of-00003.bin
6fcc5659bf10c2b335dc846acc6a1870  pytorch_model-00002-of-00003.bin
03ed19e6106f7228f6a5c103a8684450  pytorch_model-00003-of-00003.bin
```
