### ISSUE TITLE
在复现信息抽取时遇到的报错

### ISSUE THREAD

**Issue by kevinyee628** [zjunlp/KnowLM#33]
您好，我在复现信息抽取时遇到了报错，不知道是不是我环境的问题
![KNOW](https://github.com/zjunlp/KnowLM/assets/32407736/b6ee7e56-a974-4de7-9eb2-fb41ebeb27d3)

**Comment by kevinyee628** [comment]
好像是./zhixi下面权重的问题，我再尝试解决一下: )

**Comment by MikeDean2367** [comment]
您好，欢迎您的关注，请根据下面的步骤来解决：

1. 请确保您已经合并权重得到`zhixi`且已经下载LoRA权重；
2. 根据您的报错信息，请尝试使用`zhixi`和`lora`的绝对路径来传入到命令行

如果上述都不能解决，请告知我 :)

**Comment by kevinyee628** [comment]
> 您好，欢迎您的关注，请根据下面的步骤来解决：
> 
> 1. 请确保您 **已经合并权重** 得到`zhixi`且已经 **下载LoRA权重** ；
> 2. 根据您的报错信息，请尝试使用`zhixi`和`lora`的 **绝对路径** 来传入到命令行
> 
> 如果上述都不能解决，请告知我 :)

好的，谢谢！已经定位到错误，合并权重的问题

**Comment by kevinyee628** [comment]
python tools/weight_diff.py recover --path_raw ./llama-13b-hf --path_diff ./zhixi-13b-diff --path_tuned ./zhixi
  File "tools/weight_diff.py", line 26
    path_raw: str, path_tuned: str, path_diff: str, device="cpu",  # "cuda" or "cpu"
            ^
SyntaxError: invalid syntax
您好，我在合并权重的时候遇到了这样的问题，重新按照readme配置了环境，但是还是会出现如上情况

**Comment by MikeDean2367** [comment]
您好，您是否修改过`weight_diff.py`文件呢，我这边测试正常的，方便提供一下您的`weight_diff.py`文件吗？

**Comment by kevinyee628** [comment]
> 您好，您是否修改过`weight_diff.py`文件呢，我这边测试正常的，方便提供一下您的`weight_diff.py`文件吗？

您好，我没有修改过'weight_diff.py'，报错后我从仓库中复制了一份代码，但是还是不行
[weight_diff.txt](https://github.com/zjunlp/KnowLM/files/11964844/weight_diff.txt)

**Comment by MikeDean2367** [comment]
是一开始执行的时候马上就报这个错误吗？可以把完整的错误分享一下吗，这个错误是说python语法问题，我这边一切正常。

**Comment by kevinyee628** [comment]
> 是一开始执行的时候马上就报这个错误吗？可以把完整的错误分享一下吗，这个错误是说python语法问题，我这边一切正常。

嗯嗯，是的，上面那个就是完整的错误 ，一开始执行的时候就报这个错误了，会不会是我python版本的问题，我的python版本是3.9.6

**Comment by MikeDean2367** [comment]
你好，我重新配置了一下环境，使用`python=3.9.6`进行，一切也都是正常的。

**Comment by MikeDean2367** [comment]
您可以尝试一下把`make_diff`函数删除，观察是否会报错

**Comment by kevinyee628** [comment]
> 您可以尝试一下把`make_diff`函数删除，观察是否会报错

好的，收到，我尝试一下

**Comment by zxlzr** [comment]
请问您的问题解决了吗

**Comment by kevinyee628** [comment]
> 请问您的问题解决了吗

还没，可能是我的环境有问题，今天刚刚重新排查问题

**Comment by zxlzr** [comment]
您的问题解决了吗
