### ISSUE TITLE
预训练最后的模型很小正常么？

### ISSUE THREAD

**Issue by twwch** [zjunlp/KnowLM#34]
<img width="1055" alt="image" src="https://github.com/zjunlp/KnowLM/assets/44161003/d589694e-78d2-4ca4-8afd-9a4c5dec029d">

<img width="687" alt="image" src="https://github.com/zjunlp/KnowLM/assets/44161003/c7293936-3766-4e88-9c84-1e05f2073d38">

**Comment by MikeDean2367** [comment]
您好，这是不正常的。您可以看看`checkpoint-2500`文件夹里的文件大小是否正常。

**Comment by twwch** [comment]
> 

checkpoint-2500里面
![image](https://github.com/zjunlp/KnowLM/assets/44161003/3a4f6ad2-2ff0-4cfa-ae10-34690b9ba1ea)

**Comment by MikeDean2367** [comment]
您好，那有可能是在最后保存的时候出现了问题，请您做好相关文件的备份，将`train.py`文件中的第175行代码`trainer.train(resume_from_checkpoint=model_args.resume_path if model_args.resume_path != None else False)`删除，观察生成的模型文件大小是否合理，如果合理，则可能的原因如下：

1. 磁盘空间不足导致
2. 程序被意外终止

如果不合理，请告知我。

**Comment by twwch** [comment]
> 您好，那有可能是在最后保存的时候出现了问题，请您做好相关文件的备份，将`train.py`文件中的第175行代码`trainer.train(resume_from_checkpoint=model_args.resume_path if model_args.resume_path != None else False)`删除，观察生成的模型文件大小是否合理，如果合理，则可能的原因如下：
> 
> 1. 磁盘空间不足导致
> 2. 程序被意外终止
> 
> 如果不合理，请告知我。

注释掉生成的模型也不对
![image](https://github.com/zjunlp/KnowLM/assets/44161003/f2dba695-0efd-4f61-bbcc-93370de6b461)

**Comment by MikeDean2367** [comment]
您好，很抱歉，由于我们的预训练没有训练完一个epoch，因此没有执行到函数`safe_save_model_for_hf_trainer`，该函数确实存在问题。如果您着急使用的话，可以参考[此处](https://github.com/lm-sys/FastChat/issues/508)。预计下午测试修改并提交。最后感谢您的反馈。也欢迎提交PR。 :)

**Comment by zxlzr** [comment]
您好，该函数存在bug目前正在修复中，非常抱歉给您带来了不便。

**Comment by twwch** [comment]
> 此处

好的，辛苦

**Comment by twwch** [comment]
> 您好，该函数存在bug目前正在修复中，非常抱歉给您带来了不便。

多谢

**Comment by MikeDean2367** [comment]
您好，已经修复了。

**Comment by zzhang0179** [comment]
我想问一下，这样训练出来的模型是不是就不用后续合并原权重了。

**Comment by MikeDean2367** [comment]
您好，如果是您自己按照这种方式训练的话，就不用合并原来的权重了，可以直接使用。

**Comment by twwch** [comment]
> 

好的，我试试

**Comment by twwch** [comment]
> 您好，已经修复了。

好的，我试试

**Comment by twwch** [comment]
> > 您好，已经修复了。
> 
> 好的，我试试

![image](https://github.com/zjunlp/KnowLM/assets/44161003/e5cea6c4-838a-451d-b5f9-fee826a4ef65)
zheng c正常了，感谢

**Comment by zzhang0179** [comment]
我想问一下这种checkpoint是怎么保存的

**Comment by MikeDean2367** [comment]
> 我想问一下这种checkpoint是怎么保存的

您好，如果您指的是多卡的情况下如何保存的（代码中会有一个判断，仅主进程才执行保存的相关操作），您可以阅读huggingface提供的trainer的相关源码，在训练过程中的保存是由huggingface的trainer隐式保存的（即仅需设置参数`save_steps`参数即可），对于训练完成后的保存是显式执行代码`trainer.save_model(output_dir=training_args.output_dir)`来保存的。
