### ISSUE TITLE
关于pretrain阶段的问题

### ISSUE THREAD

**Issue by zzhang0179** [zjunlp/KnowLM#35]
1.我尝试打印pretrain阶段的dataset，发现input和label是一致的，为什么在这里label不是后移一个呢？
<img width="577" alt="image" src="https://github.com/zjunlp/KnowLM/assets/72484291/52366a81-b1a1-4ee5-bda1-ef8fc95dc36c">

<img width="1070" alt="image" src="https://github.com/zjunlp/KnowLM/assets/72484291/3387284b-e064-4d9a-a34f-ecb26d165693">

2. 我尝试得到model.forward的值，但报错权重矩阵不是2维的，尝试输出model.named_parameters输出的参数tensor为空是为什么？
<img width="345" alt="image" src="https://github.com/zjunlp/KnowLM/assets/72484291/3c96ad58-4dce-4da0-8e4a-61a9560d857c">
<img width="795" alt="image" src="https://github.com/zjunlp/KnowLM/assets/72484291/5de27090-05d5-4a45-ad59-f30ffd49ee99">

**Comment by MikeDean2367** [comment]
您好，感谢您的关注。

关于第一个问题，您可以查看huggingface的模型的官方实现，可以参考[此处](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L707)。

关于第二个问题，我看您的代码与您的表述不太一致，关于为什么`model.named_parameters()`的输出是空的，您这行代码是添加在哪里的呢?

**Comment by MikeDean2367** [comment]
我推测您的`model.named_parameters()`可能放在trainer初始化之后，您可以阅读huggingface的tranier的源码和deepspeed的相关介绍，我的印象中启用了`deepspeed`的话，这个model就会被一个deepspeed的类再度封装，所以会无法输出值。

在之前的[issue](https://github.com/zjunlp/KnowLM/issues/34)中，有人提到最后保存的时候模型大小很小，主要是因为我们使用的是[这个函数](https://github.com/zjunlp/KnowLM/blob/main/pretrain/train.py#L47)，这个函数里面对trainer.model.state_dict()进行保存，而这个保存的结果并没有权重信息。

**Comment by zzhang0179** [comment]
第一个问题感谢您的解答！

**Comment by zzhang0179** [comment]
第一个问题感谢您的解答！
第二个问题后续我在training.py的train()函数加载模型后尝试输出模型的参数，如下：
"""实例化模型"""
    model = transformers.AutoModelForCausalLM.from_pretrained(
        model_args.model_name_or_path,
        # cache_dir=training_args.cache_dir,
    )
    for name, param in model.named_parameters( ):
        print(name,param)
并注释了后续的所有代码，但还是得到了参数为空的情况

**Comment by zzhang0179** [comment]
我在deepspeed-chat的step1阶段加载后添加了同样的代码，并加载相同的模型，deepspeed-chat那边是可以输出模型权重的，我对比模型加载函数调用了同样的接口，不知道为什么。

**Comment by MikeDean2367** [comment]
您好，我使用了下面的代码：
```python
import transformers
model = transformers.AutoModelForCausalLM.from_pretrained(
    "decapoda-research/llama-7b-hf"
)
for name, param in model.named_parameters( ):
    print(name,param)
```
结果是正常的，参数不为空。

**Comment by MikeDean2367** [comment]
> 我在deepspeed-chat的step1阶段加载后添加了同样的代码，并加载相同的模型，deepspeed-chat那边是可以输出模型权重的，我对比模型加载函数调用了同样的接口，不知道为什么。

关于`deepspeed-chat`，我暂时还没有接触过，您可以去`deepspeed`仓库询问一下。

**Comment by zzhang0179** [comment]
请问您启用了deepspeed框架吗？如果没有的话可能确实是deepspeed框架的封装问题

**Comment by MikeDean2367** [comment]
> 请问您启用了deepspeed框架吗？如果没有的话可能确实是deepspeed框架的封装问题

我刚才提到的代码没用用到`deepspeed`，就是一个`python`文件，然后只有这6行代码 :)

**Comment by zzhang0179** [comment]
好的，感谢解答！

**Comment by zzhang0179** [comment]
https://github.com/zjunlp/KnowLM/blob/05f96372ac86e14ec52d7f71e82d90f88a416f36/pretrain/preprocess.py#L261C1-L261C1
为什么在做这行的时候没有对中文开头的29871进行判断去除呢

**Comment by MikeDean2367** [comment]
您好，您可以使用llama原始的分词器对“白日依山尽”和“白”“日”“依”“山”“尽”进行分词（相当于分6次，第一次是对整个句子，后面5次是逐个字分词），您可以看到逐个字分词的开头都会有29871，但是对整个句子的分词只有开头有29871。

如果把上面例子中的每个字比作一个句子，最大长度为3的话，按照原来的直接拼接的方法会出现3个29871，我们会去除后面的29871来提高解码效率。对于为什么会保留文档开头的29871，我个人感觉29871对于中文而言是个较为重要的token，因为29871后面跟的大概率是中文词汇，所以我们保留了开头的29871。

当然您也可以尝试都去除，如果有新的发现，请告知我 :)
