### ISSUE TITLE
权重恢复MD5不一致

### ISSUE THREAD

**Issue by Syejang** [zjunlp/KnowLM#37]
您好，我在恢复权重的时候，LLAMA的MD5一致，转换也没遇到问题，zhixi-13B-diff-fp16的MD5也一致。但是恢复的权重MD5和readme中的不一致，请问可以怎么解决呢？

**Comment by MikeDean2367** [comment]
您可以尝试使用下面的命令来下载llama-13b：
```shell
python tools/download.py --specify --download_path ./llama-13b
```
我们又再次尝试了一下，并没有发现什么问题。
如果您使用该方法仍然出现了不一致，请告知我 :)
