### ISSUE TITLE
关系抽取是否可以自定义两种实体类型的关系类型

### ISSUE THREAD

**Issue by alohaltj** [zjunlp/KnowLM#40]
比如下面这种形式["实体类型1","实体类型2"]:"关系类型1"
["症状","手术"]:"治疗"

**Comment by guihonghao** [comment]
我们在指令训练的时候没有采用这种格式的指令，我们采用的是["实体类型1","实体类型2",...]做NER、["关系类型1","关系类型2",...]做RE。

**Comment by zxlzr** [comment]
您可以自行构造这类指令的数据进行训练，模型应该就可以遵循这类指令了
