### ISSUE TITLE
RE指令微调英文数据集

### ISSUE THREAD

**Issue by TIANYUZHOU** [zjunlp/KnowLM#41]
请问您构造的RE指令微调的数据集是没有公开的吗？

**Comment by zxlzr** [comment]
您好英文的数据是基于学术数据集训练的，中文的部分数据使用了ccks比赛数据将在近日公开。

**Comment by TIANYUZHOU** [comment]
好的谢谢

**Comment by zxlzr** [comment]
您好，指令微调的部分数据集已开源https://github.com/zjunlp/KnowLM/blob/main/README_ZH.md ，其余数据均可从公开渠道下载
