### ISSUE TITLE
尝试部署vllm服务出错

### ISSUE THREAD

**Issue by funs690** [zjunlp/KnowLM#42]
尝试使用给的脚本执行时，程序出错

Traceback (most recent call last):
  File "/home/fzq/source/KnowLM/inference/launch_vllm.py", line 229, in <module>
    prompter = Prompter(args.template_path)
  File "/home/fzq/source/KnowLM/inference/utils.py", line 12, in __init__
    raise ValueError(f"Can't read {template_path}")
ValueError: Can't read data/templates/alpaca.json

修改过脚本
CUDA_VISIBLE_DEVICES=0,3 python inference/launch_vllm.py \
    --port 8090 \
    --model ./zhixi \
    --use-np-weights \
    --max-num-batched-tokens $max_num_batched_tokens \
    --dtype half \
    --tensor-parallel-size 2

疑问： 这个--model参数是啥

**Comment by funs690** [comment]
文档中对./data文件夹及相关内容没有描述，这个可以补充说明下吗

**Comment by funs690** [comment]
部署后 Init model 一直没成功，也没出错，加载的是合并diff权重的模型，这个加载模型要多久的样子，gpu上也没出现对应的进程信息，看上去像是没挂载。/is_ready接口能正常访问，返回false

gpu为2张V100， “0,3”为GPU索引，cmd如下：

max_num_batched_tokens=8000

CUDA_VISIBLE_DEVICES=0,3 python inference/launch_vllm.py \
    --port 8090 \
    --model ./zhixi \
    --use-np-weights \
    --max-num-batched-tokens $max_num_batched_tokens \
    --dtype half \
    --tensor-parallel-size 2 \
    --template_path ./finetune/lora/templates/alpaca.json

日志如下：
Init model
INFO:     Started server process [164862]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)
2023-07-26 02:23:41,289 INFO worker.py:1621 -- Started a local Ray instance.
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
(Worker pid=166713) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 11x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 11x across cluster]
(Worker pid=166713) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 11x across cluster]
(Worker pid=166713) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166713) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 11x across cluster]
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166713) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 11x across cluster]
(Worker pid=166713) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166713) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166713) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166713) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166713) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 11x across cluster]
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166713) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 11x across cluster]
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 11x across cluster]
(Worker pid=166713) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 11x across cluster]
(Worker pid=166713) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 11x across cluster]
INFO:     10.190.73.205:65263 - "GET /is_ready HTTP/1.1" 200 OK
INFO:     10.190.73.205:65263 - "GET /is_ready HTTP/1.1" 200 OK
(Worker pid=166712) [W socket.cpp:601] [c10d] The IPv6 network addresses of (__internal_head__, 13104) cannot be retrieved (gai error: -3 - Temporary failure in name resolution). [repeated 10x across cluster]
INFO:     10.190.73.205:65263 - "GET /is_ready HTTP/1.1" 200 OK


不确定是不是这个ip v6的问题， ipv4端口已监听
tcp        0      0 0.0.0.0:8090            0.0.0.0:*               LISTEN      164862/python

**Comment by funs690** [comment]
部署服务异常终止，日志如下：

Init model
INFO:     Started server process [169453]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9090 (Press CTRL+C to quit)
2023-07-26 02:42:33,879 INFO worker.py:1621 -- Started a local Ray instance.
INFO:     10.190.73.205:1380 - "GET /is_ready HTTP/1.1" 200 OK
progress sent_to_model=1 recv_from_model=0
INFO:     10.190.73.205:1386 - "GET /is_ready HTTP/1.1" 200 OK
INFO:     10.190.73.205:1386 - "GET /is_ready HTTP/1.1" 200 OK
INFO:     10.190.73.205:1386 - "GET /is_ready HTTP/1.1" 200 OK
INFO:     10.190.73.205:1386 - "GET /is_ready HTTP/1.1" 200 OK
INFO:     10.190.73.205:1386 - "GET /is_ready HTTP/1.1" 200 OK
INFO:     10.190.73.205:1386 - "GET /is_ready HTTP/1.1" 200 OK
INFO:     10.190.73.205:1386 - "GET /is_ready HTTP/1.1" 200 OK
Model ready
INFO 07-26 02:54:26 scheduler.py:269] Throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/fzq/anaconda3/envs/zhixi/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/fzq/source/KnowLM/inference/launch_vllm.py", line 82, in _thread
    vllm_outputs = server.step()
  File "/home/fzq/source/KnowLM/inference/llm_engine.py", line 243, in step
    seq_group_metadata_list, scheduler_outputs = self.scheduler.schedule()
ValueError: too many values to unpack (expected 2)
[2023-07-26 02:55:26,881 E 169453 171295] gcs_rpc_client.h:547: Failed to connect to GCS within 60 seconds. GCS may have been killed. It's either GCS is terminated by `ray stop` or is killed unexpectedly. If it is killed unexpectedly, see the log file gcs_server.out. https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure. The program will terminate.

**Comment by Alexzhuan** [comment]
您好，

想请问你当前的vllm版本是什么？我们当前实现是基于vllm==0.1.1的；我们也注意到vllm==0.1.2做较多改动，导致不兼容我们当前的实现；我们将更新我们的vllm服务的代码以适配最新版本的vllm。

**Comment by luyuntao92** [comment]
> 您好，感谢您的关注。
> 
> 关于第一个问题，`--model`为您要部署上线的模型，比如智析模型的地址，或者llama模型的地址。
> 
> 关于第二个问题，该文件位于[此处](https://github.com/zjunlp/KnowLM/blob/main/finetune/lora/templates/alpaca.json)，您可以使用绝对路径来指定。

你好，如果想使用zhixi-lora的模型进行vllm推理加速，是把lora权重和zhixi进行合并，再加载就可以了吗

**Comment by funs690** [comment]
> 您好，
> 
> 想请问你当前的vllm版本是什么？我们当前实现是基于vllm==0.1.1的；我们也注意到vllm==0.1.2做较多改动，导致不兼容我们当前的实现；我们将更新我们的vllm服务的代码以适配最新版本的vllm。

用到是vllm 0.1.2版本，我还0.1.1试试

**Comment by funs690** [comment]
> 您好，
> 
> 想请问你当前的vllm版本是什么？我们当前实现是基于vllm==0.1.1的；我们也注意到vllm==0.1.2做较多改动，导致不兼容我们当前的实现；我们将更新我们的vllm服务的代码以适配最新版本的vllm。

使用vllm 0.1.1版本的话少依赖

Traceback (most recent call last):
  File "/home/fzq/source/KnowLM/inference/launch_vllm.py", line 16, in <module>
    from llm_engine import LLMEngine
  File "/home/fzq/source/KnowLM/inference/llm_engine.py", line 12, in <module>
    from vllm.transformers_utils.tokenizer import detokenize_incrementally, get_tokenizer
ModuleNotFoundError: No module named 'vllm.transformers_utils'

**Comment by Alexzhuan** [comment]
您好，

不好意思哈，`KnowLM/inference/llm_engine.py`的代码我们的同学已经做了一些修改，这里需要麻烦你回退到我们之前版本的代码 [llm_engine.py](https://github.com/zjunlp/KnowLM/blob/45226e4966a14fcc0b4476afe72c7f7e373af6d5/inference/llm_engine.py)，做如下修改：
```python
# line 12
from vllm.transformers_utils.tokenizer import detokenize_incrementally, get_tokenizer

# 将上面这行代码改为如下
from vllm.engine.tokenizer_utils import detokenize_incrementally, get_tokenizer
```

**Comment by funs690** [comment]
> 您好，
> 
> 不好意思哈，`KnowLM/inference/llm_engine.py`的代码我们的同学已经做了一些修改，这里需要麻烦你回退到我们之前版本的代码 [llm_engine.py](https://github.com/zjunlp/KnowLM/blob/45226e4966a14fcc0b4476afe72c7f7e373af6d5/inference/llm_engine.py)，做如下修改：
> 
> ```python
> # line 12
> from vllm.transformers_utils.tokenizer import detokenize_incrementally, get_tokenizer
> 
> # 将上面这行代码改为如下
> from vllm.engine.tokenizer_utils import detokenize_incrementally, get_tokenizer
> ```

按照您的方式修改，已经可以了。使用0.1.1版本可以启动服务，谢谢
