### ISSUE TITLE
请问一下什么时候可以支持 llama.cpp量化呢

### ISSUE THREAD

**Issue by twwch** [zjunlp/KnowLM#43]

**Comment by zxlzr** [comment]
您好， 感谢您的建议knowlm将在近期支持llama.cpp量化

**Comment by twwch** [comment]
参考https://github.com/ggerganov/llama.cpp，我完成了量化了，但是感觉推理速度反而下降了

python convert.py /data/chenhao/models/mymodel
./quantize /data/chenhao/models/mymodel/ggml-model-f32.bin  /data/chenhao/models/mymodel/ggml-model-q4_0.bin q4_0

**Comment by MikeDean2367** [comment]
您好，您使用的命令是跑在CPU上的，因此可能较慢，`llama.cpp`官方提供了`cuda`版本，您可以参考官方的步骤进行量化，具体可以参考[此处](https://github.com/ggerganov/llama.cpp#cublas)和[此处](https://kubito.dev/posts/llama-cpp-linux-nvidia/)的帮助。
