### ISSUE TITLE
vllm服务请求速度较慢

### ISSUE THREAD

**Issue by funs690** [zjunlp/KnowLM#46]
vllm api请求速度单次在10s以上，并且返回的数据存在重复或者多个结果

入参：
{
    "instruction": "你好",
    "input": "",
    "parameters": {
        "top_p": 0.7,
        "max_tokens":256
    }
}

返回：
{
    "generated_text": " 你好 ，我很高兴认识你 ，我是 ______ （自我介绍）。\n\ndef meet(name):\n\t\"\"\"\n\tBelow is an instruction that describes a task.  Write a response that appropriately completes the request.\n\t \n\t ### Instruction:\n\t你好\n\t \n\t ### Response:\n\t你好 ，我很高兴认识你 ，我是 ______ （自我介绍）。\n\t\"\"\"\n\tprint(\"你好 ，我很高兴认识你 ，我是 {} 。\".format(name))</s>",
    "num_output_tokens_cf": 158,
    "error": null
}

**Comment by twwch** [comment]
相同的问题，慢，而且答非所问
![image](https://github.com/zjunlp/KnowLM/assets/44161003/a5e80c13-cec0-48d0-a9a4-fbbba7e02e0c)

**Comment by zxlzr** [comment]
您好，根据输出情况判断可能是您的模型合并部分出现了问题，我们正在抓紧排查这部分问题

**Comment by funs690** [comment]
> 您好，根据输出情况判断可能是您的模型合并部分出现了问题，我们正在抓紧排查这部分问题

会不会是peft的版本太低导致的，合并lora的时候出现了api错误，更新pert的版本后可以了

**Comment by Alexzhuan** [comment]
> > 您好，根据输出情况判断可能是您的模型合并部分出现了问题，我们正在抓紧排查这部分问题
> 
> 会不会是peft的版本太低导致的，合并lora的时候出现了api错误，更新pert的版本后可以了

您好，您在更新peft版本 (#45 ) 后重新合并LoRA是否还存在生成效果很差的情况？如果还存在，我们将进一步排查，这里也感谢您提供的建议；

对于vLLM推理速度较慢的情况，我们的运行环境在两张3090上做tensor parallel：常规英文内容推理响应大概在1-2s左右，长一些的要久一些；而在中文上推理，要比英文上要慢一些，部分原因在于我们当前版本的ZhiXi-13b未考虑中文扩词表，导致中文分词后token数量相对较长，因而增加了推理响应时间；近期，我们也会针对中文推理进行优化。

**Comment by zxlzr** [comment]
请问您问题是否已解决？
