### ISSUE TITLE
ie_cases卡住了

### ISSUE THREAD

**Issue by hupidong** [zjunlp/KnowLM#48]
zhixi-13b-base
fp32

复现信息抽取任务的时候卡住了，无法生成答案。合成的zhixi-13b-base和lora文件的md5是匹配的。
ps: 预训练模型可以正常生成。

**Comment by MikeDean2367** [comment]
您好，请问您是否有足够的内存或显存呢？如果是在CPU上跑速度会较慢

**Comment by hupidong** [comment]
> 

你好，用的gpu, 24G显存，--load_8bit=True。一直没反应，也没爆显存。

**Comment by MikeDean2367** [comment]
您好，您可以尝试一些简单的case(您可以使用web的方法进行，仅输入token数量较少的instruction，如“今天天气怎么样”，不输入input)，或者调小最大生成长度，或者使用CPU来进行，来排除是代码本身问题还是GPU显存的问题 :)

**Comment by hupidong** [comment]
> 您好，您可以尝试一些简单的case(您可以使用web的方法进行，仅输入token数量较少的instruction，如“今天天气怎么样”，不输入input)，或者调小最大生成长度，或者使用CPU来进行，来排除是代码本身问题还是GPU显存的问题 :)

你好，解决了，我把peft从0.2.0（requirements.txt中版本）版本升级到目前最新的0.4.0版本就可以。
