### ISSUE TITLE
测试网站所有尝试的入口均显示 Error

### ISSUE THREAD

**Issue by tdingquan** [zjunlp/KnowLM#49]
这是被攻击了吗

- 当前在线人数：555
- 所有问题都显示 Error
  
![image](https://github.com/zjunlp/KnowLM/assets/30195295/4da3584c-931a-4f3c-b970-abee870fe017)

- 项目 git clone 一直失败，显示 github timed out

**Comment by zxlzr** [comment]
您好是服务器宕机了，那个555是累计访问的计数器，我们会尽快恢复服务

**Comment by zxlzr** [comment]
http://knowlm.zjukg.cn/demo 您好服务除了知识编辑之外均已恢复
