### ISSUE TITLE
合并后的推理问题

### ISSUE THREAD

**Issue by hupidong** [zjunlp/KnowLM#50]
你好，合并zhixi-13b-base和lora权重后，使用tgi进行推理，发现回答效果很差，感觉lora没有合并成功的样子。
请问能否把合并后的文件的md5发出来？

ps: vllm没有试，因为显存不够。

合并参考：
python tools/export_hf_checkpoint.py \
    --base_model data/zhixi-13b \
    --lora_model data/zhixi-13b-lora \
    --output_dir data/zhixi-13b-merged

tgi推理：
USE_FLASH_ATTENTION=true CUDA_VISIBLE_DEVICES=0 text-generation-launcher \
    --port 8080 \
    --model-id $MODEL_NAME \
    --quantize bitsandbytes \
    --num-shard 1 \
    --max-input-length 512 \
    --max-total-tokens 1024 \
    --max-batch-total-tokens 4096 \
    --max-batch-prefill-tokens 4096 \
    --max-waiting-tokens 7 \
    --waiting-served-ratio 1.2

input: 你好

输出讲了一个大约两三百字的小故事。

**Comment by MikeDean2367** [comment]
下面提供了以`diff-fp32`为底座合并后的MD5：
```shell
c0230438c93b1453654ee8c7b94abe27  pytorch_model-00001-of-00006.bin
4f1f006a75492882e9517250091bc922  pytorch_model-00002-of-00006.bin 
50e5a7dd9c62a3d8177dd572504d000c  pytorch_model-00003-of-00006.bin
56ea18a76bb826f2f516e9d8f7aa21a7  pytorch_model-00004-of-00006.bin
19fc756668d83a806bf8e588624950bc  pytorch_model-00005-of-00006.bin
64cd76f113069fd7a720eb4c67d6b2a9  pytorch_model-00006-of-00006.bin
```

**Comment by hupidong** [comment]
> Reference

**Comment by hupidong** [comment]
> 下面提供了以`diff-fp32`为底座合并后的MD5：
> 
> ```shell
> c0230438c93b1453654ee8c7b94abe27  pytorch_model-00001-of-00006.bin
> 4f1f006a75492882e9517250091bc922  pytorch_model-00002-of-00006.bin 
> 50e5a7dd9c62a3d8177dd572504d000c  pytorch_model-00003-of-00006.bin
> 56ea18a76bb826f2f516e9d8f7aa21a7  pytorch_model-00004-of-00006.bin
> 19fc756668d83a806bf8e588624950bc  pytorch_model-00005-of-00006.bin
> 64cd76f113069fd7a720eb4c67d6b2a9  pytorch_model-00006-of-00006.bin
> ```


你好，为啥我这边合并后有28个切片呢。

**Comment by hupidong** [comment]
> > 下面提供了以`diff-fp32`为底座合并后的MD5：
> > ```shell
> > c0230438c93b1453654ee8c7b94abe27  pytorch_model-00001-of-00006.bin
> > 4f1f006a75492882e9517250091bc922  pytorch_model-00002-of-00006.bin 
> > 50e5a7dd9c62a3d8177dd572504d000c  pytorch_model-00003-of-00006.bin
> > 56ea18a76bb826f2f516e9d8f7aa21a7  pytorch_model-00004-of-00006.bin
> > 19fc756668d83a806bf8e588624950bc  pytorch_model-00005-of-00006.bin
> > 64cd76f113069fd7a720eb4c67d6b2a9  pytorch_model-00006-of-00006.bin
> > ```
> 
> 你好，为啥我这边合并后有28个切片呢。

你好，设置了一下切片的大小，个数对上了，但是md5对不上。
53d574fd4e8c0839746a4190fbe9d23f  ./pytorch_model-00001-of-00006.bin
3362e214dc313155fa90ed03c4ae971e  ./pytorch_model-00002-of-00006.bin
9ec86cf68e78bb81135f104be18192df  ./pytorch_model-00003-of-00006.bin
b86e801ad5ebd8ac209b3c046e6c01df  ./pytorch_model-00004-of-00006.bin
8e4cbadac5da6b3ebb5883740d531389  ./pytorch_model-00005-of-00006.bin
1ab8b4d62572c3a6a77e67e3fcf15a3d  ./pytorch_model-00006-of-00006.bin

**Comment by hupidong** [comment]
你好，可以把合并lora后的完整模型放出来吗？

**Comment by zxlzr** [comment]
您好，合并后的大模型已开源，相关文档正在更新中

底座大模型：https://huggingface.co/zjunlp/knowlm-13b-base-v1.0

智析抽取大模型：https://huggingface.co/zjunlp/knowlm-13b-zhixi

智析抽取大模型(加强版，弱化通用能力):  https://huggingface.co/zjunlp/knowlm-13b-ke

后续即将更新v1.1版本

**Comment by hupidong** [comment]
> 您好，合并后的大模型已开源，相关文档正在更新中
> 
> 底座大模型：https://huggingface.co/zjunlp/knowlm-13b-base-v1.0
> 
> 智析抽取大模型：https://huggingface.co/zjunlp/knowlm-13b-zhixi
> 
> 智析抽取大模型(加强版，弱化通用能力): https://huggingface.co/zjunlp/knowlm-13b-ke
> 
> 后续即将更新v1.1版本

感谢！
