### ISSUE TITLE
ImportError: cannot import name 'DeviceID' from 'vllm.engine.ray_utils'

### ISSUE THREAD

**Issue by Haoran1234567** [zjunlp/KnowLM#53]
inference/llm_engine.py , line 11, in <module>
    from vllm.engine.ray_utils import DeviceID, initialize_cluster, ray

ImportError: cannot import name 'DeviceID' from 'vllm.engine.ray_utils'

**Comment by Alexzhuan** [comment]
您好，

您需要安装vLLM==0.1.2。

**Comment by Haoran1234567** [comment]
好的，不报这个错了，谢谢

**Comment by Haoran1234567** [comment]
利用vllm来部署项目接口，我看model path只有一个，不像信息抽取复现结果中zhixi和lora利用peft分开加载。所有我vllm部署三元组抽取的话，这个model直接用合成zhixi-sft？

**Comment by Alexzhuan** [comment]
您好，如果要部署vllm服务，LoRA的参数要与Zhixi模型的参数进行合并

**Comment by 211250243** [comment]
请问安装vLLM==0.1.2时，报错：  RuntimeError: Cannot find CUDA_HOME. CUDA must be available in order to build the package.
但是我设置了CUDA_HOME的，cuda版本是11.6，为什么还是 Cannot find？
