### ISSUE TITLE
预训练阶段，data 和label

### ISSUE THREAD

**Issue by wangxg666** [zjunlp/KnowLM#54]
代码里 label = data.clone(), 这里不需要把label shift + 1 么？

**Comment by MikeDean2367** [comment]
您好，感谢您的关注。

这个过程是由`transformers`包实现的，您可以参考这个[issue](https://github.com/zjunlp/KnowLM/issues/35)。由于`huggingface`更新了`llama2`的代码，因此这一行的代码位于[此处](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L834)。
