### ISSUE TITLE
7b大概需要多少显存，以及啥时候发布？很期待

### ISSUE THREAD

**Issue by jieli1990** [zjunlp/KnowLM#56]
如题

**Comment by zxlzr** [comment]
您好，和常规7b需要的显存相差不大，我们扩充了中文词表。预计时间在8月底或9月初，目前仍在训练优化。

**Comment by jieli1990** [comment]
感谢，支持

**Comment by SaraiQX** [comment]
同期待。团队好棒呀，vllm和开源模型都想到了，特别赞 ❤️❤️ 需要算力的话 我有认识一位老师或许可以帮到
