### ISSUE TITLE
请问，zhixi-13b在cpp量化的时候需要修改哪些变量？

### ISSUE THREAD

**Issue by guoxiaoyue111111** [zjunlp/KnowLM#57]
![image](https://github.com/zjunlp/KnowLM/assets/45383666/a9203ded-e943-4c59-a155-ef0f7c79d86a)

您好，在2.4 Llama.cpp量化的时候，使用命令如下：
python tools/download.py --specify --download_path ./your/path --repo_name zjunlp/knowlm-13b-zhixi
该命令中除了需要将./your/path改为本地存储模型的路径外，还需要有别的修改吗？

另外，
然后将[此处](https://github.com/ggerganov/llama.cpp#prepare-data--run)的模型路径更换为下载的路径即可。在具体运行的时候，请修改[此脚本](https://github.com/ggerganov/llama.cpp/blob/master/examples/alpaca.sh)的模型路径即可。
“此脚本”中需要改哪个路径？

非常感谢，期待您的回复～

**Comment by MikeDean2367** [comment]
您好，对于第一个问题，没有其他需要修改的。对于第二个问题，您需要将第一步下载的文件，按照`llama.cpp`的步骤量化完成后，将`./models/alpaca.13b.ggmlv3.q8_0.bin`更改为量化后的路径即可。
