### ISSUE TITLE
抽取模型结果异常问题（解决中）

### ISSUE THREAD

**Issue by SupritYoung** [zjunlp/KnowLM#58]
你好！我在本地运行了 Zhixi-IE-13B，实际运行发现对于训练集以外的数据抽取能力非常有限，而且一直输出无用内容（似乎是泄露数据？），请问是我哪里设置的不对，还是什么问题？
```
query = "你认为下面这段文本可能包含哪些信息，请以三元组的格式（[头实体，关系，尾实体]）输出。\n“朱元璋（1328 年 -1398 年），明朝开国皇帝，原名朱重八，后取名兴宗，汉族，濠州钟离（今安徽凤阳）人。他自幼贫寒，父母兄长均死于瘟疫，孤苦无依，入皇觉寺为小沙弥，后参加了起义军，并改名朱元璋，意为诛灭元朝的璋。他 25 岁时参加郭子兴领导的红巾军反抗元朝暴政，逐渐成为军队的主要领导者。经过长达十年的战争，他最终击败了最后的对手，建立了明朝，成为了开国皇帝。在位期间，他进行了一系列政治、经济和军事改革，奠定了明朝长达近 300 年的基础。他被认为是中国历史上最伟大的皇帝之一，被尊称为洪武帝。”\n候选关系类型有[是,出生于,加入,击败,别称,参加了,进行了]"
```
output:
```
输入中包含的关系三元组是：
[朱元璋,出生于,濠州钟离],[朱元璋,出生于,安徽凤阳],[朱元璋,出生于,钟离],[朱元璋,击败,元朝),(朱元璋,参加了,起义军),(朱元璋,别称,洪武帝),(朱元璋,别称,洪武帝),(朱元璋,参加了,起义军) 农业综合开发贷款
农业综合开发贷款是指国家为了支持农业发展，由国家银行向农业部门提供的，用于农业综合开发项目的贷款。
农业综合开发贷款的主要目的是通过投资建设农业基础设施，改善农业生产条件，提高农业生产能力，增加农民收入，促进农业发展。
农业综合开发贷款的对象主要是农业部门的农村集体经济组织、农民合作社、农民专业合作社和农民个人。
农业综合开发贷款的期限一般为 3-5 年。贷款利率按照中国人民银行规定的同期同档次贷款利率执行。贷款实行按年计息，分季度或分月归
```
```
query = "你认为下面这段文本可能包含哪些信息，请以三元组的格式（[头实体，关系，尾实体]）输出。\n“乔布斯（Steve Jobs）是美国科技界著名的创业家和企业家，他是苹果公司的共同创始人之一。他于1955年出生在美国加利福尼亚州的旧金山，于2011年去世。\n乔布斯以其卓越的创新、设计和商业眼光而闻名，他在计算机科技、音乐、移动设备和动画产业等领域都有深远影响。他曾创办了苹果公司，后来又被解雇，然后再度回归，带领苹果公司取得了一系列重大的技术和商业突破。他是iMac、iTunes、iPod、iPhone和iPad等产品的推动者，这些产品深刻地改变了人们的生活方式和科技行业的格局。\n乔布斯不仅关注产品的功能性，还强调产品的设计美感和用户体验。他的演讲才华也是他的标志之一，他在苹果产品发布会上的演讲经常激发人们的兴趣和热情。\n乔布斯因其卓越的贡献被认为是现代科技产业的重要人物之一，他的影响延伸至全球范围，成为许多创业家和领袖的榜样。”"
res, _ = chat_model.chat(query)
print(res)
```
output:
```
输入中包含的关系三元组是：
[乔布斯，关系，Steve Jobs] 钱益铭，字冰霞，浙江钱塘人，清末民初政治人物。 光绪三十一年（1905年），他中举人。 后来他加入同盟会。 民国成立后，他历任浙江省教育厅厅长、浙江省财政厅厅长、财政部顾问、全国财政委员会委员等职。 民国二十四年（1935年），他任国民政府财政部顾问。.... the the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the a
```

**Comment by zxlzr** [comment]
请问您用的是哪个模型，没有Zhixi-IE-13B这个模型 <img width="852" alt="image" src="https://github.com/zjunlp/KnowLM/assets/1264492/b2c0a558-a44f-4486-bb11-285f11f2e9da">

**Comment by MikeDean2367** [comment]
您好，您可以尝试从以下方面进行尝试：

1. 超参数。建议您尝试不同的超参数进行。
2. 模板。您可以参考[此处](https://github.com/zjunlp/KnowLM/blob/main/README_ZH.md#2-2)的第3点的内容，尝试使用我们提供的输入模板进行。
3. 模型。您可以尝试一下我们的`KnowLM-13B-ZhiXi`模型。

如果以上仍不行，请告知我们 :)

**Comment by zxlzr** [comment]
> 你好！我在本地运行了 Zhixi-IE-13B，实际运行发现对于训练集以外的数据抽取能力非常有限，而且一直输出无用内容（似乎是泄露数据？），请问是我哪里设置的不对，还是什么问题？
> 
> ```
> query = "你认为下面这段文本可能包含哪些信息，请以三元组的格式（[头实体，关系，尾实体]）输出。\n“朱元璋（1328 年 -1398 年），明朝开国皇帝，原名朱重八，后取名兴宗，汉族，濠州钟离（今安徽凤阳）人。他自幼贫寒，父母兄长均死于瘟疫，孤苦无依，入皇觉寺为小沙弥，后参加了起义军，并改名朱元璋，意为诛灭元朝的璋。他 25 岁时参加郭子兴领导的红巾军反抗元朝暴政，逐渐成为军队的主要领导者。经过长达十年的战争，他最终击败了最后的对手，建立了明朝，成为了开国皇帝。在位期间，他进行了一系列政治、经济和军事改革，奠定了明朝长达近 300 年的基础。他被认为是中国历史上最伟大的皇帝之一，被尊称为洪武帝。”\n候选关系类型有[是,出生于,加入,击败,别称,参加了,进行了]"
> ```
> 
> output:
> 
> ```
> 输入中包含的关系三元组是：
> [朱元璋,出生于,濠州钟离],[朱元璋,出生于,安徽凤阳],[朱元璋,出生于,钟离],[朱元璋,击败,元朝),(朱元璋,参加了,起义军),(朱元璋,别称,洪武帝),(朱元璋,别称,洪武帝),(朱元璋,参加了,起义军) 农业综合开发贷款
> 农业综合开发贷款是指国家为了支持农业发展，由国家银行向农业部门提供的，用于农业综合开发项目的贷款。
> 农业综合开发贷款的主要目的是通过投资建设农业基础设施，改善农业生产条件，提高农业生产能力，增加农民收入，促进农业发展。
> 农业综合开发贷款的对象主要是农业部门的农村集体经济组织、农民合作社、农民专业合作社和农民个人。
> 农业综合开发贷款的期限一般为 3-5 年。贷款利率按照中国人民银行规定的同期同档次贷款利率执行。贷款实行按年计息，分季度或分月归
> ```
> 
> ```
> query = "你认为下面这段文本可能包含哪些信息，请以三元组的格式（[头实体，关系，尾实体]）输出。\n“乔布斯（Steve Jobs）是美国科技界著名的创业家和企业家，他是苹果公司的共同创始人之一。他于1955年出生在美国加利福尼亚州的旧金山，于2011年去世。\n乔布斯以其卓越的创新、设计和商业眼光而闻名，他在计算机科技、音乐、移动设备和动画产业等领域都有深远影响。他曾创办了苹果公司，后来又被解雇，然后再度回归，带领苹果公司取得了一系列重大的技术和商业突破。他是iMac、iTunes、iPod、iPhone和iPad等产品的推动者，这些产品深刻地改变了人们的生活方式和科技行业的格局。\n乔布斯不仅关注产品的功能性，还强调产品的设计美感和用户体验。他的演讲才华也是他的标志之一，他在苹果产品发布会上的演讲经常激发人们的兴趣和热情。\n乔布斯因其卓越的贡献被认为是现代科技产业的重要人物之一，他的影响延伸至全球范围，成为许多创业家和领袖的榜样。”"
> res, _ = chat_model.chat(query)
> print(res)
> ```
> 
> output:
> 
> ```
> 输入中包含的关系三元组是：
> [乔布斯，关系，Steve Jobs] 钱益铭，字冰霞，浙江钱塘人，清末民初政治人物。 光绪三十一年（1905年），他中举人。 后来他加入同盟会。 民国成立后，他历任浙江省教育厅厅长、浙江省财政厅厅长、财政部顾问、全国财政委员会委员等职。 民国二十四年（1935年），他任国民政府财政部顾问。.... the the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the and the a
> ```

建议您首选https://huggingface.co/zjunlp/knowlm-13b-zhixi 这个模型结果相对稳定一些，github readme提供的例子都是这个模型的输出，其他模型都需要调参。

**Comment by guihonghao** [comment]
你好，
```python
res, _ = chat_model.chat(query)
print(res)
```
这个调用方式是什么？我们好像并不支持这种调用方式

**Comment by zxlzr** [comment]
麻烦您可以提供一些更详细信息如使用哪个模型、使用什么方式推理及超参数以便于我们帮您解决问题

**Comment by SupritYoung** [comment]
非常抱歉，我可能没有描述清楚我的问题。我使用的模型为`knowlm-13b-ie`。考虑到knowlm也是基于llama开发的，调用方式我用的是自己之前撰写的运行 LLaMA的代码，模板采用 llama 的默认模板。推理方式就是正常生产，`temperature=0.95`。我再去尝试一下 `KnowLM-13B-ZhiXi`，随后给您反馈。感谢作者的热心回复！

**Comment by guihonghao** [comment]
1、knowlm-13b-ie需要搭配alpaca中的template使用。
2、我们建议采用的指令使用我们训练中所采用的指令格式，可以参考 
https://github.com/zjunlp/DeepKE/blob/main/example/llm/InstructKGC/kg2instruction/README.md
当然如果使用训练中未见过的指令格式，模型也是具有一定泛化性的（我们有测试部分样例）。
3、knowlm-13b-ie需要指定抽取关系列表，如果不指定列表或列表为空，模型将输出NAN，这是knowlm-13b-ie的缺陷，也是我们下一步改进的方向。
感想您的关注

**Comment by 12210122** [comment]
> 

问题3是否在KnowLM-7B-ie中得到了缓解呢？我发现如果需要提取的实体很多的情况下，由于模型的输出速度似乎很慢，因此在需要输出一大堆NAN的情况下，一次问答需要的时长要有20多秒，不知道从LLaMA1换到LLaMA2代速度会不会变快一点

**Comment by guihonghao** [comment]
这是设计上的问题，针对句子中不存在的关系，有两种选择。要么1、输出NAN（例如：(NAN,面积,NAN),(NAN,事件,NAN),(东京大清真寺基金会,创建时间,1997年)），要么2、不输出（例如：(东京大清真寺基金会,创建时间,1997年)）。
第一种情况确实存在输出过于慢的问题，我们会在KnowLM-7B-ie中考虑使用第二种设计。

**Comment by SupritYoung** [comment]
目前我的工作恰好需要非指定关系的开放信息抽取。请教一下，如果我在你们模型的基础上在大规模的不含有关系类型的数据上训练，结果会怎么样？是否会与之前的能力冲突？

**Comment by SupritYoung** [comment]
BTW，非常感谢你们的工作，我们如果有工作基于你们的项目做出来一定会大力致谢，开源分享。

**Comment by zxlzr** [comment]
> 目前我的工作恰好需要非指定关系的开放信息抽取。请教一下，如果我在你们模型的基础上在大规模的不含有关系类型的数据上训练，结果会怎么样？是否会与之前的能力冲突？

目前我们没有优化和测试过开放信息抽取，如果为了避免能力冲突的话您也可以从底座开始加载数据训练https://huggingface.co/zjunlp/knowlm-13b-base-v1.0

**Comment by guihonghao** [comment]
“如果我在你们模型的基础上在大规模的不含有关系类型的数据上训练，结果会怎么样？是否会与之前的能力冲突？”，这个我们没有测试过，我们的想法是在训练中就纳入“非指定关系的开放信息抽取”的指令，让模型同时具备“非指定关系的开放信息抽取”和“指定关系的信息抽取”的能力。

**Comment by SupritYoung** [comment]
也就是说一份数据造两个信息抽取的指令，一个包含关系列表，另一个不包含，对么？

**Comment by guihonghao** [comment]
可以这样做，也可以对于A%的指令包含关系列表，（1-A）% 的指令不包含。毕竟中英文IE指令数据量挺大的。

**Comment by guihonghao** [comment]
可以这样做，也可以对于A%的指令包含关系列表，（1-A）% 的指令不包含。毕竟中英文IE指令数据量挺大的。
