### ISSUE TITLE
请教cpp量化问题

### ISSUE THREAD

**Issue by guoxiaoyue111111** [zjunlp/KnowLM#60]
您好，我在执行以下命令时出现问题：
![image](https://github.com/zjunlp/KnowLM/assets/45383666/60d14660-4605-4c79-80bc-2162a9089ce8)
具体报错信息如下：
![image](https://github.com/zjunlp/KnowLM/assets/45383666/2146bf10-6f30-485b-bbb3-0c63b85956c4)
麻烦您帮忙看下是什么问题，期待您的回复，谢谢~

**Comment by MikeDean2367** [comment]
您好，这个看起来似乎是网络问题（进度条显示下载11个文件，但是现在只下载了5个文件），建议您重新多次运行这个命令。如果仍然有问题，请告知我 :)

**Comment by guoxiaoyue111111** [comment]
非常感谢您的回复！

但是，我尝试多次之后，仍然是报这个错。而且我在执行
<img width="1352" alt="截屏2023-08-23 21 14 05" src="https://github.com/zjunlp/KnowLM/assets/45383666/516f16fb-f5f5-4c8c-87c8-ece130630a52">
这个命令的时候也是报网络错误，手动打开https://huggingface.co/docs/transformers/installation#offline-mode这个链接是可以的，所以，“进度条显示下载11个文件，但是现在只下载了5个文件”，会不会是因为内存不够了，所以只能下载5个文件。我使用的mac m1 16G。

**Comment by MikeDean2367** [comment]
您可以去https://huggingface.co/zjunlp/knowlm-13b-zhixi，手动下载文件，看看是否可以呢？

**Comment by guoxiaoyue111111** [comment]
您好，我上面的问题可能表述的不太清楚，导致目前还没有能够解决，我把我的运行和需求重新描述一下。

参考：https://github.com/zjunlp/KnowLM/blob/main/README_ZH.md 中的操作步骤
需求：使用Lora微调后的模型实现信息抽取
环境：Mac m1 内存 16G

当前问题：在执行python examples/generate_lora_web.py --base_model zjunlp/knowlm-13b-zhixi 命令时由于显存不够报错，因为knowlm-13b-zhixi 需要24G，但电脑只有16G。所以考虑使用量化，量化后13B模型只占7.8G，现在已经手动将zjunlp/knowlm-13b-zhixi 下载到本地，接下来如何操作可以完成量化？

**Comment by MikeDean2367** [comment]
您好，您可以参考`llama.cpp`的readme。首先参考[此处](https://github.com/ggerganov/llama.cpp#build)配置环境，然后参考[此处](https://github.com/ggerganov/llama.cpp#prepare-data--run)进行量化，具体的使用可以参考我们的readme和llama.cpp的readme。

**Comment by guoxiaoyue111111** [comment]
您好，按照您的建议，我进行了如下操作：

1、配置环境
git clone https://kgithub.com/ggerganov/llama.cpp
cd llama.cpp
make

2、量化操作
ls ./models
13B tokenizer_checklist.chk tokenizer.model ggml-vocab-llama.gguf
# 将本地下载的knowlm-13b-zhixi放到models的目录下，重命名为13B，从https://huggingface.co/nyanko7/LLaMA-7B/tree/3b94aad3d8e39981b81e14239446d935b6dbf2bd下载tokenizer_checklist.chk tokenizer.model这两个文件到models目录
python3 -m pip install -r requirements.txt
python3 convert.py models/13B/ 

目前执行到convert.py的时候报错：
(zhixi) guoxiaoyue@guoxiaoyuedeMacBook-Pro 9-llama.cpp % python3 convert.py models/13B/
Loading model file models/13B/pytorch_model-00001-of-00003.bin
Loading model file models/13B/pytorch_model-00001-of-00003.bin
Loading model file models/13B/pytorch_model-00002-of-00003.bin
Loading model file models/13B/pytorch_model-00003-of-00003.bin
Traceback (most recent call last):
  File "/Users/guoxiaoyue/Desktop/my buaa/9-llama.cpp/convert.py", line 1111, in <module>
    main()
  File "/Users/guoxiaoyue/Desktop/my buaa/9-llama.cpp/convert.py", line 1062, in main
    params = Params.load(model_plus)
  File "/Users/guoxiaoyue/Desktop/my buaa/9-llama.cpp/convert.py", line 254, in load
    params = Params.loadHFTransformerJson(model_plus.model, hf_config_path)
  File "/Users/guoxiaoyue/Desktop/my buaa/9-llama.cpp/convert.py", line 173, in loadHFTransformerJson
    if "rope_scaling" in config and config["rope_scaling"].get("type") == "linear":
AttributeError: 'NoneType' object has no attribute 'get'
这个问题在llama.cpp的项目的issue中有人提出，但是讨论全是英文没看懂，麻烦问您一下有没有遇到这个报错，请问是怎么解决的？

**Comment by MikeDean2367** [comment]
您好，[此处](https://github.com/ggerganov/llama.cpp#prepare-data--run)的步骤不需要执行convert步骤，因为我们提供的模型是符合hf格式的。直接进行量化即可，运行的步骤参考[此处](https://github.com/zjunlp/KnowLM/blob/main/README_ZH.md#14-llamacpp%E9%87%8F%E5%8C%96)。
