### ISSUE TITLE
lora?KnowLM-13B-ZhiXi?

### ISSUE THREAD

**Issue by mkzzz** [zjunlp/KnowLM#61]
代码里启动lora的web，把lora的weight加载去掉了？意思是KnowLM-13B-ZhiXi和KnowLM-13B-IE都是全参数微调的吗？但是我看后面的训练细节里写，抽取的ner/re/ee都是用的lora训练的，有点懵。全参数微调的有训练脚本吗？

**Comment by zxlzr** [comment]
您好，模型是lora训的，已经帮您合并好了所以无需加载lora权重了，

**Comment by mkzzz** [comment]
> 您好，模型是lora训的，已经帮您合并好了所以无需加载lora权重了，

哦，明白了，感谢回答。

**Comment by mkzzz** [comment]
``
