### ISSUE TITLE
demo 所有功能显示超时错误？

### ISSUE THREAD

**Issue by purpletpig** [zjunlp/KnowLM#65]
![image](https://github.com/zjunlp/KnowLM/assets/41353245/9bffcb51-4fb3-4d3b-923a-89e48c74f82e)

**Comment by zxlzr** [comment]
您好，建议您重试下，我这里显示是正常的。另外我们近期在对抽取模型进行更新，抽取的结果可能会临时有一些异常，请见谅。

**Comment by zxlzr** [comment]
如果您仍无法访问请告知我
