### ISSUE TITLE
直接拉取镜像，按步骤操作，OSError报错

### ISSUE THREAD

**Issue by Hubotcoder** [zjunlp/KnowLM#66]
CUDA SETUP: Required library version not found: libsbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
/opt/conda/envs/zhixi/lib/python3.9/site-packages/bitsandbytes/cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
testing ie ablities!
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /zjunlp/knowlm-13b-zhixi/resolve/main/tokenizer.model (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4ce6521e20>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: c32e891b-367c-40d8-b2fc-bb6ab10b1dc7)')' thrown while requesting HEAD https://huggingface.co/zjunlp/knowlm-13b-zhixi/resolve/main/tokenizer.model
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /zjunlp/knowlm-13b-zhixi/resolve/main/added_tokens.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4ce6521760>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 3cd78332-4108-484d-9478-123305be1ba4)')' thrown while requesting HEAD https://huggingface.co/zjunlp/knowlm-13b-zhixi/resolve/main/added_tokens.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /zjunlp/knowlm-13b-zhixi/resolve/main/special_tokens_map.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4ce64ec1c0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 343769f1-8c91-4d84-ad76-9c26d168e808)')' thrown while requesting HEAD https://huggingface.co/zjunlp/knowlm-13b-zhixi/resolve/main/special_tokens_map.json
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /zjunlp/knowlm-13b-zhixi/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4ce64ec550>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 0c75f2b6-2268-47c9-bea0-e47ff9c022f6)')' thrown while requesting HEAD https://huggingface.co/zjunlp/knowlm-13b-zhixi/resolve/main/tokenizer_config.json
Traceback (most recent call last):
  File "/app/KnowLM/examples/generate_lora.py", line 216, in <module>
    fire.Fire(main)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/app/KnowLM/examples/generate_lora.py", line 113, in main
    tokenizer = LlamaTokenizer.from_pretrained(base_model)
  File "/opt/conda/envs/zhixi/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1795, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'zjunlp/knowlm-13b-zhixi'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'zjunlp/knowlm-13b-zhixi' is the correct path to a directory containing all relevant files for a LlamaTokenizer tokenizer.

**Comment by zxlzr** [comment]
您好我们在复现您的问题，目前未成功，建议您先用git clone 安装使用

**Comment by BeasterYong** [comment]
您好，请问您是否检查您的网络代理配置？根据报错Connection to huggingface.co timed out，推测是由于国内网络无法访问huggingface.co所致，您可以在容器内配置网络代理后重试，谢谢！

**Comment by BeasterYong** [comment]
您好，请问您是否检查您的网络代理配置？根据报错Connection to huggingface.co timed out，推测是由于国内网络无法访问huggingface.co所致，您可以在容器内配置网络代理后重试，谢谢！

**Comment by zxlzr** [comment]
您好，您的问题是网络问题造成的，建议您尝试使用代理或切换网络

**Comment by Hubotcoder** [comment]
好的，谢谢
