### ISSUE TITLE
how to use lora weights

### ISSUE THREAD

**Issue by githubgtl** [zjunlp/KnowLM#67]
I train the model and get checkpoint but I dont konw how to use

**Comment by MikeDean2367** [comment]
Hi, thank you for your attention. If you want to test the performance, you can use the code [here](https://github.com/zjunlp/KnowLM/blob/main/examples/generate_lora.py), uncomment lines 123 to 127, lines 134 to 139, lines 144 to 148, and then use the following command (refer to [here](https://github.com/zjunlp/KnowLM#12-model-usage-guide)):
```bash
python examples/generate_lora.py --base_model your/base/model/path --lora_weights your/lora/weights/path --run_ie_cases
```

**Comment by githubgtl** [comment]
> Hi, thank you for your attention. If you want to test the performance, you can use the code [here](https://github.com/zjunlp/KnowLM/blob/main/examples/generate_lora.py), uncomment lines 123 to 127, lines 134 to 139, lines 144 to 148, and then use the following command (refer to [here](https://github.com/zjunlp/KnowLM#12-model-usage-guide)):
> 
> ```shell
> python examples/generate_lora.py --base_model your/base/model/path --lora_weights your/lora/weights/path --run_ie_cases
> ```

can this model do RE task

**Comment by MikeDean2367** [comment]
Our model supports RE tasks. However, whether the model you've trained can support RE tasks depends on whether your training data includes them.

**Comment by githubgtl** [comment]
> model you've trained can support RE tasks depends on whether your training data includes them.

your project can give RE prompt and evalate metric script

**Comment by githubgtl** [comment]
> our template can be found [here](https://github.com/zjunlp/KnowLM/blob/main/examples/ie_prompt.py).

I see it,but its content seems to extract triple list not RE task

**Comment by MikeDean2367** [comment]
Hi, as far as I know, RE(Relation Extraction) should refer to triple extraction. You can refer to [here](https://zhuanlan.zhihu.com/p/581760225) for more information. For other questions, we can communicate on WeChat(my WeChat ID is `Oxygen2367`).
