### ISSUE TITLE
预训练

### ISSUE THREAD

**Issue by xiaoma444** [zjunlp/KnowLM#69]
您好，请问我想要使用自己的保密数据，使用lora网页版时效果差，我想要用自己的数据预训练模型，应该看哪篇文档，或者具体应该如何操作？

**Comment by MikeDean2367** [comment]
您好，您可以使用lora进行训练，具体参考[此处](https://github.com/zjunlp/KnowLM/tree/main/finetune/lora)

**Comment by zxlzr** [comment]
您好，您可以使用lora进行进一步训练。

**Comment by xiaoma444** [comment]
想达到抽取效果时，数据处理格式应该为什么，处理完的数据路径应该在哪里，以及finetune.py中的data_path需要修改吗？感谢帮助

**Comment by MikeDean2367** [comment]
您好，详细的信息位于[此处](https://github.com/zjunlp/KnowLM/tree/main/finetune/lora#%E8%BF%90%E8%A1%8C)，包括数据处理格式(格式参见链接)、数据路径(任意路径均可)和`data_path`(可以通过命令行参数，或者在代码中设置默认值)。如果还有其他不明白的地方，请告知我 :)

**Comment by xiaoma444** [comment]
我想要完成抽取任务，那我等价的数据应该怎么表示呢?例如：中国联通委托其它企业代为维护的动力系统设备（以下简称“委外代维”或“维护外包”），应按照本规程的要求与代维单位签订代维协议。我想要抽取其中的组织机构，然后输出联通之类的。

**Comment by zxlzr** [comment]
您好， 这两者形式达到的目的是一样的，前者常见于传统的抽取模型如序列标注模型，后者可以用于大模型做端到端生成式抽取。
