### ISSUE TITLE
New Example file 

### ISSUE THREAD

**Issue by ayan-joshi** [zjunlp/KnowLM#76]
I would like to add a new python file in the example folder which will be a preprocessor.py file 

Please assign me this issue I will work on it under hacktoberfest label @zxlzr

**Comment by zxlzr** [comment]
Thanks for your advice, this is really cool!

**Comment by ayan-joshi** [comment]
> Thanks for your advice, this is really cool!

it would be great if u add the hacktoberfest label to it  @zxlzr
