### ISSUE TITLE
下载超时

### ISSUE THREAD

**Issue by SongWWWWWW** [zjunlp/KnowLM#80]
在执行这条命令时：python examples/generate_finetune.py --base_model zjunlp/knowlm-13b-base-v1.0
发现下载超时了，该如何解决

[错误信息.txt](https://github.com/zjunlp/KnowLM/files/12882269/default.txt)

**Comment by MikeDean2367** [comment]
您好，应该是网络不稳定的问题。

如果您使用的是windows或者带有图形界面的linux，您可以直接访问[此处](https://huggingface.co/zjunlp/knowlm-13b-base-v1.0/tree/main)，手动下载里面的文件，然后将这些文件放置到一个文件夹，最后更改`--base_model`的路径为您的文件夹路径即可。

如果您使用的是服务器，对于大型的文件（LFS标记），您需要在浏览器上访问上面的地址，然后将鼠标移动到`LFS`标记处，单击右键，然后复制下载链接，最后在服务器上执行`wget -c url`即可，此处的`-c`表示接力下载，即即使下载中断，下次会接着从上次下载的地方继续下载，而不是重新下载。以`pytorch_model-00001-of-00003.bin`文件为例，其对应的下载命令为：
```shell
# 注意下载url不是https://huggingface.co/zjunlp/knowlm-13b-base-v1.0/blob/main/pytorch_model-00001-of-00003.bin
wget -c https://huggingface.co/zjunlp/knowlm-13b-base-v1.0/resolve/main/pytorch_model-00001-of-00003.bin
```
然后将下载的文件放在一个文件夹，更改`--base_model`的路径为您的文件夹路径即可。

如果您还有其他问题，请告知我 :)
