### ISSUE TITLE
您好，经过测试，device="cpu"，python examples/generate_finetune_web.py --base_model ./model/knowlm-13b-base-v1.0中产生的RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'问题解决了。

### ISSUE THREAD

**Issue by jia95812** [zjunlp/KnowLM#81]
您好，经过测试，device="cpu"，python examples/generate_finetune_web.py --base_model ./model/knowlm-13b-base-v1.0中产生的RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'问题解决了。
但是如果在generate_lora_web.py中设置device="cpu"，并使用python examples/generate_lora_web.py --base_model ./model/knowlm-13b-zhixi，仍然会产生RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'的错误，估计是上次修改中没有完全修改完善，请帮忙查看一下，非常感谢！

_Originally posted by @jia95812 in https://github.com/zjunlp/KnowLM/issues/73#issuecomment-1761256073_

**Comment by MikeDean2367** [comment]
您好，已经修复了，如果仍有问题，请告知我 :)
