### ISSUE TITLE
RuntimeError: "addmm_impl_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by Qiuxsi** [zjunlp/KnowLM#82]
虽然 generate_finetune_web.py 和 generate_lora_web.py 已经修复了这个问题，但是 generate_finetune.py 和 generate_lora.py 在 CPU 上跑貌似还会有这个报错没有人遇到吗，不知道是不是我的问题

**Comment by MikeDean2367** [comment]
您好，感谢您的反馈，我们已经修复这个问题了，如果仍有问题请告知我 :)
