### ISSUE TITLE
Feature: Adding contributors section to the README.md file. 

### ISSUE THREAD

**Issue by Kalyanimhala** [zjunlp/KnowLM#89]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/zjunlp/KnowLM/assets/147402107/71e519c7-4e38-484b-be8f-9cf04b4bcf1b)

**Comment by Kalyanimhala** [comment]
@zxlzr Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by zxlzr** [comment]
Thanks. I have assigned the issue.
