### ISSUE TITLE
请问下是否支持非中英语种的任务？

### ISSUE THREAD

**Issue by fishfree** [zjunlp/KnowLM#92]
非常感谢如此慷慨、开放的贡献！！

想问一下：是不是基于llama/ transformers架构的预训练模型都可以支持？如果是，可否提供一下详细的步骤？特别是这个支持德语的模型：https://huggingface.co/Babelscape/rebel-large?text=Punta+Cana+is+a+resort+town+in+the+municipality+of+Higuey%2C+in+La+Altagracia+Province%2C+the+eastern+most+province+of+the+Dominican+Republic

**Comment by MikeDean2367** [comment]
您好，感谢您的关注。

我们的预训练代码目前仅支持Decoder-Only的架构，比如Llama系列等，这种架构的预训练步骤可以参考[此处](https://github.com/zjunlp/KnowLM/tree/main/pretrain)的readme。

然后是您提到的那个链接，根据[config.json](https://huggingface.co/Babelscape/rebel-large/blob/main/config.json)，这是一个BART模型，是一个Encoder-Decoder架构，我们目前的代码并不直接支持这一点，但是理论上来说，只要更改数据输入的部分即可快速的适应Encoder-Decoder架构的训练。如果您实现了这一点，欢迎提交PR。

如果您还有其他问题，请告知我 :)

**Comment by fishfree** [comment]
@MikeDean2367 谢谢您的解答。我现在的功力还不会自己训练。我先试试您说的README里的步骤吧。再次感谢你们慷慨的开源贡献！

**Comment by zxlzr** [comment]
您后续如果有任何问题欢迎随时提问
